LIDL Soundboard: D:/Qt/Projects/Lidl_Soundboard/lib/bass.h File Reference
bass.h File Reference
#include <stdint.h>
Classes
struct BASS_DEVICEINFO
struct BASS_INFO
struct BASS_RECORDINFO
struct BASS_SAMPLE
struct BASS_CHANNELINFO
struct BASS_PLUGINFORM
struct BASS_PLUGININFO
struct BASS_3DVECTOR
struct BASS_FILEPROCS
struct TAG_ID3
struct TAG_APE_BINARY
struct TAG_BEXT
struct TAG_CART_TIMER
struct TAG_CART
struct TAG_CUE_POINT
struct TAG_CUE
struct TAG_SMPL_LOOP
struct TAG_SMPL
struct TAG_CA_CODEC
struct tWAVEFORMATEX
struct BASS_DX8_CHORUS
struct BASS_DX8_COMPRESSOR
struct BASS_DX8_DISTORTION
struct BASS_DX8_ECHO
struct BASS_DX8_FLANGER
struct BASS_DX8_GARGLE
struct BASS_DX8_I3DL2REVERB
struct BASS_DX8_PARAMEQ
struct BASS_DX8_REVERB
struct BASS_FX_VOLUME_PARAM
Macros
#define WINAPI
#define CALLBACK
#define TRUE 1
#define FALSE 0
#define LOBYTE(a) (BYTE)(a)
#define HIBYTE(a) (BYTE)((a)>>8)
#define LOWORD(a) (WORD)(a)
#define HIWORD(a) (WORD)((a)>>16)
#define MAKEWORD(a, b) (WORD)(((a)&0xff)|((b)<<8))
#define MAKELONG(a, b) (DWORD)(((a)&0xffff)|((b)<<16))
#define BASSVERSION 0x204
#define BASSVERSIONTEXT "2.4"
#define BASSDEF(f) WINAPI f
#define BASS_OK 0
#define BASS_ERROR_MEM 1
#define BASS_ERROR_FILEOPEN 2
#define BASS_ERROR_DRIVER 3
#define BASS_ERROR_BUFLOST 4
#define BASS_ERROR_HANDLE 5
#define BASS_ERROR_FORMAT 6
#define BASS_ERROR_POSITION 7
#define BASS_ERROR_INIT 8
#define BASS_ERROR_START 9
#define BASS_ERROR_SSL 10
#define BASS_ERROR_ALREADY 14
#define BASS_ERROR_NOCHAN 18
#define BASS_ERROR_ILLTYPE 19
#define BASS_ERROR_ILLPARAM 20
#define BASS_ERROR_NO3D 21
#define BASS_ERROR_NOEAX 22
#define BASS_ERROR_DEVICE 23
#define BASS_ERROR_NOPLAY 24
#define BASS_ERROR_FREQ 25
#define BASS_ERROR_NOTFILE 27
#define BASS_ERROR_NOHW 29
#define BASS_ERROR_EMPTY 31
#define BASS_ERROR_NONET 32
#define BASS_ERROR_CREATE 33
#define BASS_ERROR_NOFX 34
#define BASS_ERROR_NOTAVAIL 37
#define BASS_ERROR_DECODE 38
#define BASS_ERROR_DX 39
#define BASS_ERROR_TIMEOUT 40
#define BASS_ERROR_FILEFORM 41
#define BASS_ERROR_SPEAKER 42
#define BASS_ERROR_VERSION 43
#define BASS_ERROR_CODEC 44
#define BASS_ERROR_ENDED 45
#define BASS_ERROR_BUSY 46
#define BASS_ERROR_UNKNOWN -1
#define BASS_CONFIG_BUFFER 0
#define BASS_CONFIG_UPDATEPERIOD 1
#define BASS_CONFIG_GVOL_SAMPLE 4
#define BASS_CONFIG_GVOL_STREAM 5
#define BASS_CONFIG_GVOL_MUSIC 6
#define BASS_CONFIG_CURVE_VOL 7
#define BASS_CONFIG_CURVE_PAN 8
#define BASS_CONFIG_FLOATDSP 9
#define BASS_CONFIG_3DALGORITHM 10
#define BASS_CONFIG_NET_TIMEOUT 11
#define BASS_CONFIG_NET_BUFFER 12
#define BASS_CONFIG_PAUSE_NOPLAY 13
#define BASS_CONFIG_NET_PREBUF 15
#define BASS_CONFIG_NET_PASSIVE 18
#define BASS_CONFIG_REC_BUFFER 19
#define BASS_CONFIG_NET_PLAYLIST 21
#define BASS_CONFIG_MUSIC_VIRTUAL 22
#define BASS_CONFIG_VERIFY 23
#define BASS_CONFIG_UPDATETHREADS 24
#define BASS_CONFIG_DEV_BUFFER 27
#define BASS_CONFIG_VISTA_TRUEPOS 30
#define BASS_CONFIG_IOS_MIXAUDIO 34
#define BASS_CONFIG_DEV_DEFAULT 36
#define BASS_CONFIG_NET_READTIMEOUT 37
#define BASS_CONFIG_VISTA_SPEAKERS 38
#define BASS_CONFIG_IOS_SPEAKER 39
#define BASS_CONFIG_MF_DISABLE 40
#define BASS_CONFIG_HANDLES 41
#define BASS_CONFIG_UNICODE 42
#define BASS_CONFIG_SRC 43
#define BASS_CONFIG_SRC_SAMPLE 44
#define BASS_CONFIG_ASYNCFILE_BUFFER 45
#define BASS_CONFIG_OGG_PRESCAN 47
#define BASS_CONFIG_MF_VIDEO 48
#define BASS_CONFIG_AIRPLAY 49
#define BASS_CONFIG_DEV_NONSTOP 50
#define BASS_CONFIG_IOS_NOCATEGORY 51
#define BASS_CONFIG_VERIFY_NET 52
#define BASS_CONFIG_DEV_PERIOD 53
#define BASS_CONFIG_FLOAT 54
#define BASS_CONFIG_NET_SEEK 56
#define BASS_CONFIG_AM_DISABLE 58
#define BASS_CONFIG_NET_PLAYLIST_DEPTH 59
#define BASS_CONFIG_NET_PREBUF_WAIT 60
#define BASS_CONFIG_NET_AGENT 16
#define BASS_CONFIG_NET_PROXY 17
#define BASS_CONFIG_IOS_NOTIFY 46
#define BASS_DEVICE_8BITS 1
#define BASS_DEVICE_MONO 2
#define BASS_DEVICE_3D 4
#define BASS_DEVICE_16BITS 8
#define BASS_DEVICE_LATENCY 0x100
#define BASS_DEVICE_CPSPEAKERS 0x400
#define BASS_DEVICE_SPEAKERS 0x800
#define BASS_DEVICE_NOSPEAKER 0x1000
#define BASS_DEVICE_DMIX 0x2000
#define BASS_DEVICE_FREQ 0x4000
#define BASS_DEVICE_STEREO 0x8000
#define BASS_DEVICE_HOG 0x10000
#define BASS_DEVICE_AUDIOTRACK 0x20000
#define BASS_DEVICE_DSOUND 0x40000
#define BASS_OBJECT_DS 1
#define BASS_OBJECT_DS3DL 2
#define BASS_DEVICE_ENABLED 1
#define BASS_DEVICE_DEFAULT 2
#define BASS_DEVICE_INIT 4
#define BASS_DEVICE_LOOPBACK 8
#define BASS_DEVICE_TYPE_MASK 0xff000000
#define BASS_DEVICE_TYPE_NETWORK 0x01000000
#define BASS_DEVICE_TYPE_SPEAKERS 0x02000000
#define BASS_DEVICE_TYPE_LINE 0x03000000
#define BASS_DEVICE_TYPE_HEADPHONES 0x04000000
#define BASS_DEVICE_TYPE_MICROPHONE 0x05000000
#define BASS_DEVICE_TYPE_HEADSET 0x06000000
#define BASS_DEVICE_TYPE_HANDSET 0x07000000
#define BASS_DEVICE_TYPE_DIGITAL 0x08000000
#define BASS_DEVICE_TYPE_SPDIF 0x09000000
#define BASS_DEVICE_TYPE_HDMI 0x0a000000
#define BASS_DEVICE_TYPE_DISPLAYPORT 0x40000000
#define BASS_DEVICES_AIRPLAY 0x1000000
#define DSCAPS_CONTINUOUSRATE 0x00000010
#define DSCAPS_EMULDRIVER 0x00000020
#define DSCAPS_CERTIFIED 0x00000040
#define DSCAPS_SECONDARYMONO 0x00000100
#define DSCAPS_SECONDARYSTEREO 0x00000200
#define DSCAPS_SECONDARY8BIT 0x00000400
#define DSCAPS_SECONDARY16BIT 0x00000800
#define DSCCAPS_EMULDRIVER DSCAPS_EMULDRIVER
#define DSCCAPS_CERTIFIED DSCAPS_CERTIFIED
#define WAVE_FORMAT_1M08 0x00000001 /* 11.025 kHz, Mono, 8-bit */
#define WAVE_FORMAT_1S08 0x00000002 /* 11.025 kHz, Stereo, 8-bit */
#define WAVE_FORMAT_1M16 0x00000004 /* 11.025 kHz, Mono, 16-bit */
#define WAVE_FORMAT_1S16 0x00000008 /* 11.025 kHz, Stereo, 16-bit */
#define WAVE_FORMAT_2M08 0x00000010 /* 22.05 kHz, Mono, 8-bit */
#define WAVE_FORMAT_2S08 0x00000020 /* 22.05 kHz, Stereo, 8-bit */
#define WAVE_FORMAT_2M16 0x00000040 /* 22.05 kHz, Mono, 16-bit */
#define WAVE_FORMAT_2S16 0x00000080 /* 22.05 kHz, Stereo, 16-bit */
#define WAVE_FORMAT_4M08 0x00000100 /* 44.1 kHz, Mono, 8-bit */
#define WAVE_FORMAT_4S08 0x00000200 /* 44.1 kHz, Stereo, 8-bit */
#define WAVE_FORMAT_4M16 0x00000400 /* 44.1 kHz, Mono, 16-bit */
#define WAVE_FORMAT_4S16 0x00000800 /* 44.1 kHz, Stereo, 16-bit */
#define BASS_SAMPLE_8BITS 1
#define BASS_SAMPLE_FLOAT 256
#define BASS_SAMPLE_MONO 2
#define BASS_SAMPLE_LOOP 4
#define BASS_SAMPLE_3D 8
#define BASS_SAMPLE_SOFTWARE 16
#define BASS_SAMPLE_MUTEMAX 32
#define BASS_SAMPLE_VAM 64
#define BASS_SAMPLE_FX 128
#define BASS_SAMPLE_OVER_VOL 0x10000
#define BASS_SAMPLE_OVER_POS 0x20000
#define BASS_SAMPLE_OVER_DIST 0x30000
#define BASS_STREAM_PRESCAN 0x20000
#define BASS_STREAM_AUTOFREE 0x40000
#define BASS_STREAM_RESTRATE 0x80000
#define BASS_STREAM_BLOCK 0x100000
#define BASS_STREAM_DECODE 0x200000
#define BASS_STREAM_STATUS 0x800000
#define BASS_MP3_IGNOREDELAY 0x200
#define BASS_MP3_SETPOS BASS_STREAM_PRESCAN
#define BASS_MUSIC_FLOAT BASS_SAMPLE_FLOAT
#define BASS_MUSIC_MONO BASS_SAMPLE_MONO
#define BASS_MUSIC_LOOP BASS_SAMPLE_LOOP
#define BASS_MUSIC_3D BASS_SAMPLE_3D
#define BASS_MUSIC_FX BASS_SAMPLE_FX
#define BASS_MUSIC_AUTOFREE BASS_STREAM_AUTOFREE
#define BASS_MUSIC_DECODE BASS_STREAM_DECODE
#define BASS_MUSIC_PRESCAN BASS_STREAM_PRESCAN
#define BASS_MUSIC_CALCLEN BASS_MUSIC_PRESCAN
#define BASS_MUSIC_RAMP 0x200
#define BASS_MUSIC_RAMPS 0x400
#define BASS_MUSIC_SURROUND 0x800
#define BASS_MUSIC_SURROUND2 0x1000
#define BASS_MUSIC_FT2PAN 0x2000
#define BASS_MUSIC_FT2MOD 0x2000
#define BASS_MUSIC_PT1MOD 0x4000
#define BASS_MUSIC_NONINTER 0x10000
#define BASS_MUSIC_SINCINTER 0x800000
#define BASS_MUSIC_POSRESET 0x8000
#define BASS_MUSIC_POSRESETEX 0x400000
#define BASS_MUSIC_STOPBACK 0x80000
#define BASS_MUSIC_NOSAMPLE 0x100000
#define BASS_SPEAKER_FRONT 0x1000000
#define BASS_SPEAKER_REAR 0x2000000
#define BASS_SPEAKER_CENLFE 0x3000000
#define BASS_SPEAKER_REAR2 0x4000000
#define BASS_SPEAKER_N(n) ((n)<<24)
#define BASS_SPEAKER_LEFT 0x10000000
#define BASS_SPEAKER_RIGHT 0x20000000
#define BASS_SPEAKER_FRONTLEFT BASS_SPEAKER_FRONT|BASS_SPEAKER_LEFT
#define BASS_SPEAKER_FRONTRIGHT BASS_SPEAKER_FRONT|BASS_SPEAKER_RIGHT
#define BASS_SPEAKER_REARLEFT BASS_SPEAKER_REAR|BASS_SPEAKER_LEFT
#define BASS_SPEAKER_REARRIGHT BASS_SPEAKER_REAR|BASS_SPEAKER_RIGHT
#define BASS_SPEAKER_CENTER BASS_SPEAKER_CENLFE|BASS_SPEAKER_LEFT
#define BASS_SPEAKER_LFE BASS_SPEAKER_CENLFE|BASS_SPEAKER_RIGHT
#define BASS_SPEAKER_REAR2LEFT BASS_SPEAKER_REAR2|BASS_SPEAKER_LEFT
#define BASS_SPEAKER_REAR2RIGHT BASS_SPEAKER_REAR2|BASS_SPEAKER_RIGHT
#define BASS_ASYNCFILE 0x40000000
#define BASS_UNICODE 0x80000000
#define BASS_RECORD_PAUSE 0x8000
#define BASS_RECORD_ECHOCANCEL 0x2000
#define BASS_RECORD_AGC 0x4000
#define BASS_VAM_HARDWARE 1
#define BASS_VAM_SOFTWARE 2
#define BASS_VAM_TERM_TIME 4
#define BASS_VAM_TERM_DIST 8
#define BASS_VAM_TERM_PRIO 16
#define BASS_ORIGRES_FLOAT 0x10000
#define BASS_CTYPE_SAMPLE 1
#define BASS_CTYPE_RECORD 2
#define BASS_CTYPE_STREAM 0x10000
#define BASS_CTYPE_STREAM_OGG 0x10002
#define BASS_CTYPE_STREAM_MP1 0x10003
#define BASS_CTYPE_STREAM_MP2 0x10004
#define BASS_CTYPE_STREAM_MP3 0x10005
#define BASS_CTYPE_STREAM_AIFF 0x10006
#define BASS_CTYPE_STREAM_CA 0x10007
#define BASS_CTYPE_STREAM_MF 0x10008
#define BASS_CTYPE_STREAM_AM 0x10009
#define BASS_CTYPE_STREAM_DUMMY 0x18000
#define BASS_CTYPE_STREAM_DEVICE 0x18001
#define BASS_CTYPE_STREAM_WAV 0x40000
#define BASS_CTYPE_STREAM_WAV_PCM 0x50001
#define BASS_CTYPE_STREAM_WAV_FLOAT 0x50003
#define BASS_CTYPE_MUSIC_MOD 0x20000
#define BASS_CTYPE_MUSIC_MTM 0x20001
#define BASS_CTYPE_MUSIC_S3M 0x20002
#define BASS_CTYPE_MUSIC_XM 0x20003
#define BASS_CTYPE_MUSIC_IT 0x20004
#define BASS_CTYPE_MUSIC_MO3 0x00100
#define BASS_3DMODE_NORMAL 0
#define BASS_3DMODE_RELATIVE 1
#define BASS_3DMODE_OFF 2
#define BASS_3DALG_DEFAULT 0
#define BASS_3DALG_OFF 1
#define BASS_3DALG_FULL 2
#define BASS_3DALG_LIGHT 3
#define EAX_PRESET_GENERIC EAX_ENVIRONMENT_GENERIC,0.5F,1.493F,0.5F
#define EAX_PRESET_PADDEDCELL EAX_ENVIRONMENT_PADDEDCELL,0.25F,0.1F,0.0F
#define EAX_PRESET_ROOM EAX_ENVIRONMENT_ROOM,0.417F,0.4F,0.666F
#define EAX_PRESET_BATHROOM EAX_ENVIRONMENT_BATHROOM,0.653F,1.499F,0.166F
#define EAX_PRESET_LIVINGROOM EAX_ENVIRONMENT_LIVINGROOM,0.208F,0.478F,0.0F
#define EAX_PRESET_STONEROOM EAX_ENVIRONMENT_STONEROOM,0.5F,2.309F,0.888F
#define EAX_PRESET_AUDITORIUM EAX_ENVIRONMENT_AUDITORIUM,0.403F,4.279F,0.5F
#define EAX_PRESET_CONCERTHALL EAX_ENVIRONMENT_CONCERTHALL,0.5F,3.961F,0.5F
#define EAX_PRESET_CAVE EAX_ENVIRONMENT_CAVE,0.5F,2.886F,1.304F
#define EAX_PRESET_ARENA EAX_ENVIRONMENT_ARENA,0.361F,7.284F,0.332F
#define EAX_PRESET_HANGAR EAX_ENVIRONMENT_HANGAR,0.5F,10.0F,0.3F
#define EAX_PRESET_CARPETEDHALLWAY EAX_ENVIRONMENT_CARPETEDHALLWAY,0.153F,0.259F,2.0F
#define EAX_PRESET_HALLWAY EAX_ENVIRONMENT_HALLWAY,0.361F,1.493F,0.0F
#define EAX_PRESET_STONECORRIDOR EAX_ENVIRONMENT_STONECORRIDOR,0.444F,2.697F,0.638F
#define EAX_PRESET_ALLEY EAX_ENVIRONMENT_ALLEY,0.25F,1.752F,0.776F
#define EAX_PRESET_FOREST EAX_ENVIRONMENT_FOREST,0.111F,3.145F,0.472F
#define EAX_PRESET_CITY EAX_ENVIRONMENT_CITY,0.111F,2.767F,0.224F
#define EAX_PRESET_MOUNTAINS EAX_ENVIRONMENT_MOUNTAINS,0.194F,7.841F,0.472F
#define EAX_PRESET_QUARRY EAX_ENVIRONMENT_QUARRY,1.0F,1.499F,0.5F
#define EAX_PRESET_PLAIN EAX_ENVIRONMENT_PLAIN,0.097F,2.767F,0.224F
#define EAX_PRESET_PARKINGLOT EAX_ENVIRONMENT_PARKINGLOT,0.208F,1.652F,1.5F
#define EAX_PRESET_SEWERPIPE EAX_ENVIRONMENT_SEWERPIPE,0.652F,2.886F,0.25F
#define EAX_PRESET_UNDERWATER EAX_ENVIRONMENT_UNDERWATER,1.0F,1.499F,0.0F
#define EAX_PRESET_DRUGGED EAX_ENVIRONMENT_DRUGGED,0.875F,8.392F,1.388F
#define EAX_PRESET_DIZZY EAX_ENVIRONMENT_DIZZY,0.139F,17.234F,0.666F
#define EAX_PRESET_PSYCHOTIC EAX_ENVIRONMENT_PSYCHOTIC,0.486F,7.563F,0.806F
#define BASS_STREAMPROC_END 0x80000000
#define STREAMPROC_DUMMY (STREAMPROC*)0
#define STREAMPROC_PUSH (STREAMPROC*)-1
#define STREAMPROC_DEVICE (STREAMPROC*)-2
#define STREAMFILE_NOBUFFER 0
#define STREAMFILE_BUFFER 1
#define STREAMFILE_BUFFERPUSH 2
#define BASS_FILEDATA_END 0
#define BASS_FILEPOS_CURRENT 0
#define BASS_FILEPOS_DECODE BASS_FILEPOS_CURRENT
#define BASS_FILEPOS_DOWNLOAD 1
#define BASS_FILEPOS_END 2
#define BASS_FILEPOS_START 3
#define BASS_FILEPOS_CONNECTED 4
#define BASS_FILEPOS_BUFFER 5
#define BASS_FILEPOS_SOCKET 6
#define BASS_FILEPOS_ASYNCBUF 7
#define BASS_FILEPOS_SIZE 8
#define BASS_FILEPOS_BUFFERING 9
#define BASS_SYNC_POS 0
#define BASS_SYNC_END 2
#define BASS_SYNC_META 4
#define BASS_SYNC_SLIDE 5
#define BASS_SYNC_STALL 6
#define BASS_SYNC_DOWNLOAD 7
#define BASS_SYNC_FREE 8
#define BASS_SYNC_SETPOS 11
#define BASS_SYNC_MUSICPOS 10
#define BASS_SYNC_MUSICINST 1
#define BASS_SYNC_MUSICFX 3
#define BASS_SYNC_OGG_CHANGE 12
#define BASS_SYNC_MIXTIME 0x40000000
#define BASS_SYNC_ONETIME 0x80000000
#define BASS_ACTIVE_STOPPED 0
#define BASS_ACTIVE_PLAYING 1
#define BASS_ACTIVE_STALLED 2
#define BASS_ACTIVE_PAUSED 3
#define BASS_ATTRIB_FREQ 1
#define BASS_ATTRIB_VOL 2
#define BASS_ATTRIB_PAN 3
#define BASS_ATTRIB_EAXMIX 4
#define BASS_ATTRIB_NOBUFFER 5
#define BASS_ATTRIB_VBR 6
#define BASS_ATTRIB_CPU 7
#define BASS_ATTRIB_SRC 8
#define BASS_ATTRIB_NET_RESUME 9
#define BASS_ATTRIB_SCANINFO 10
#define BASS_ATTRIB_NORAMP 11
#define BASS_ATTRIB_BITRATE 12
#define BASS_ATTRIB_BUFFER 13
#define BASS_ATTRIB_MUSIC_AMPLIFY 0x100
#define BASS_ATTRIB_MUSIC_PANSEP 0x101
#define BASS_ATTRIB_MUSIC_PSCALER 0x102
#define BASS_ATTRIB_MUSIC_BPM 0x103
#define BASS_ATTRIB_MUSIC_SPEED 0x104
#define BASS_ATTRIB_MUSIC_VOL_GLOBAL 0x105
#define BASS_ATTRIB_MUSIC_ACTIVE 0x106
#define BASS_ATTRIB_MUSIC_VOL_CHAN 0x200
#define BASS_ATTRIB_MUSIC_VOL_INST 0x300
#define BASS_SLIDE_LOG 0x1000000
#define BASS_DATA_AVAILABLE 0
#define BASS_DATA_FIXED 0x20000000
#define BASS_DATA_FLOAT 0x40000000
#define BASS_DATA_FFT256 0x80000000
#define BASS_DATA_FFT512 0x80000001
#define BASS_DATA_FFT1024 0x80000002
#define BASS_DATA_FFT2048 0x80000003
#define BASS_DATA_FFT4096 0x80000004
#define BASS_DATA_FFT8192 0x80000005
#define BASS_DATA_FFT16384 0x80000006
#define BASS_DATA_FFT32768 0x80000007
#define BASS_DATA_FFT_INDIVIDUAL 0x10
#define BASS_DATA_FFT_NOWINDOW 0x20
#define BASS_DATA_FFT_REMOVEDC 0x40
#define BASS_DATA_FFT_COMPLEX 0x80
#define BASS_LEVEL_MONO 1
#define BASS_LEVEL_STEREO 2
#define BASS_LEVEL_RMS 4
#define BASS_LEVEL_VOLPAN 8
#define BASS_TAG_ID3 0
#define BASS_TAG_ID3V2 1
#define BASS_TAG_OGG 2
#define BASS_TAG_HTTP 3
#define BASS_TAG_ICY 4
#define BASS_TAG_META 5
#define BASS_TAG_APE 6
#define BASS_TAG_MP4 7
#define BASS_TAG_WMA 8
#define BASS_TAG_VENDOR 9
#define BASS_TAG_LYRICS3 10
#define BASS_TAG_CA_CODEC 11
#define BASS_TAG_MF 13
#define BASS_TAG_WAVEFORMAT 14
#define BASS_TAG_AM_MIME 15
#define BASS_TAG_AM_NAME 16
#define BASS_TAG_RIFF_INFO 0x100
#define BASS_TAG_RIFF_BEXT 0x101
#define BASS_TAG_RIFF_CART 0x102
#define BASS_TAG_RIFF_DISP 0x103
#define BASS_TAG_RIFF_CUE 0x104
#define BASS_TAG_RIFF_SMPL 0x105
#define BASS_TAG_APE_BINARY 0x1000
#define BASS_TAG_MUSIC_NAME 0x10000
#define BASS_TAG_MUSIC_MESSAGE 0x10001
#define BASS_TAG_MUSIC_ORDERS 0x10002
#define BASS_TAG_MUSIC_AUTH 0x10003
#define BASS_TAG_MUSIC_INST 0x10100
#define BASS_TAG_MUSIC_SAMPLE 0x10300
#define _WAVEFORMATEX_
#define BASS_POS_BYTE 0
#define BASS_POS_MUSIC_ORDER 1
#define BASS_POS_OGG 3
#define BASS_POS_RESET 0x2000000
#define BASS_POS_RELATIVE 0x4000000
#define BASS_POS_INEXACT 0x8000000
#define BASS_POS_DECODE 0x10000000
#define BASS_POS_DECODETO 0x20000000
#define BASS_POS_SCAN 0x40000000
#define BASS_NODEVICE 0x20000
#define BASS_INPUT_OFF 0x10000
#define BASS_INPUT_ON 0x20000
#define BASS_INPUT_TYPE_MASK 0xff000000
#define BASS_INPUT_TYPE_UNDEF 0x00000000
#define BASS_INPUT_TYPE_DIGITAL 0x01000000
#define BASS_INPUT_TYPE_LINE 0x02000000
#define BASS_INPUT_TYPE_MIC 0x03000000
#define BASS_INPUT_TYPE_SYNTH 0x04000000
#define BASS_INPUT_TYPE_CD 0x05000000
#define BASS_INPUT_TYPE_PHONE 0x06000000
#define BASS_INPUT_TYPE_SPEAKER 0x07000000
#define BASS_INPUT_TYPE_WAVE 0x08000000
#define BASS_INPUT_TYPE_AUX 0x09000000
#define BASS_INPUT_TYPE_ANALOG 0x0a000000
#define BASS_FX_DX8_CHORUS 0
#define BASS_FX_DX8_COMPRESSOR 1
#define BASS_FX_DX8_DISTORTION 2
#define BASS_FX_DX8_ECHO 3
#define BASS_FX_DX8_FLANGER 4
#define BASS_FX_DX8_GARGLE 5
#define BASS_FX_DX8_I3DL2REVERB 6
#define BASS_FX_DX8_PARAMEQ 7
#define BASS_FX_DX8_REVERB 8
#define BASS_FX_VOLUME 9
#define BASS_DX8_PHASE_NEG_180 0
#define BASS_DX8_PHASE_NEG_90 1
#define BASS_DX8_PHASE_ZERO 2
#define BASS_DX8_PHASE_90 3
#define BASS_DX8_PHASE_180 4
#define BASS_IOSNOTIFY_INTERRUPT 1
#define BASS_IOSNOTIFY_INTERRUPT_END 2
Typedefs
typedef uint8_t BYTE
typedef uint16_t WORD
typedef uint32_t DWORD
typedef uint64_t QWORD
typedef int BOOL
typedef DWORD HMUSIC
typedef DWORD HSAMPLE
typedef DWORD HCHANNEL
typedef DWORD HSTREAM
typedef DWORD HRECORD
typedef DWORD HSYNC
typedef DWORD HDSP
typedef DWORD HFX
typedef DWORD HPLUGIN
typedef struct BASS_3DVECTOR BASS_3DVECTOR
typedef void * buffer
typedef void DWORD length
typedef void DWORD void * user
typedef DWORD channel
typedef DWORD DWORD data
typedef struct tWAVEFORMATEX WAVEFORMATEX
typedef struct tWAVEFORMATEX * PWAVEFORMATEX
typedef struct tWAVEFORMATEX * LPWAVEFORMATEX
typedef const WAVEFORMATEX * LPCWAVEFORMATEX
Enumerations
enum {
EAX_ENVIRONMENT_GENERIC, EAX_ENVIRONMENT_PADDEDCELL, EAX_ENVIRONMENT_ROOM, EAX_ENVIRONMENT_BATHROOM,
EAX_ENVIRONMENT_LIVINGROOM, EAX_ENVIRONMENT_STONEROOM, EAX_ENVIRONMENT_AUDITORIUM, EAX_ENVIRONMENT_CONCERTHALL,
EAX_ENVIRONMENT_CAVE, EAX_ENVIRONMENT_ARENA, EAX_ENVIRONMENT_HANGAR, EAX_ENVIRONMENT_CARPETEDHALLWAY,
EAX_ENVIRONMENT_HALLWAY, EAX_ENVIRONMENT_STONECORRIDOR, EAX_ENVIRONMENT_ALLEY, EAX_ENVIRONMENT_FOREST,
EAX_ENVIRONMENT_CITY, EAX_ENVIRONMENT_MOUNTAINS, EAX_ENVIRONMENT_QUARRY, EAX_ENVIRONMENT_PLAIN,
EAX_ENVIRONMENT_PARKINGLOT, EAX_ENVIRONMENT_SEWERPIPE, EAX_ENVIRONMENT_UNDERWATER, EAX_ENVIRONMENT_DRUGGED,
EAX_ENVIRONMENT_DIZZY, EAX_ENVIRONMENT_PSYCHOTIC, EAX_ENVIRONMENT_COUNT
}
Functions
typedef DWORD (CALLBACK STREAMPROC)(HSTREAM handle
typedef void (CALLBACK FILECLOSEPROC)(void *user)
typedef QWORD (CALLBACK FILELENPROC)(void *user)
typedef BOOL (CALLBACK FILESEEKPROC)(QWORD offset
BOOL BASSDEF() BASS_SetConfig (DWORD option, DWORD value)
DWORD BASSDEF() BASS_GetConfig (DWORD option)
BOOL BASSDEF() BASS_SetConfigPtr (DWORD option, const void *value)
void *BASSDEF() BASS_GetConfigPtr (DWORD option)
DWORD BASSDEF() BASS_GetVersion ()
int BASSDEF() BASS_ErrorGetCode ()
BOOL BASSDEF() BASS_GetDeviceInfo (DWORD device, BASS_DEVICEINFO *info)
BOOL BASSDEF() BASS_Init (int device, DWORD freq, DWORD flags, void *win, void *dsguid)
BOOL BASSDEF() BASS_SetDevice (DWORD device)
DWORD BASSDEF() BASS_GetDevice ()
BOOL BASSDEF() BASS_Free ()
BOOL BASSDEF() BASS_GetInfo (BASS_INFO *info)
BOOL BASSDEF() BASS_Update (DWORD length)
float BASSDEF() BASS_GetCPU ()
BOOL BASSDEF() BASS_Start ()
BOOL BASSDEF() BASS_Stop ()
BOOL BASSDEF() BASS_Pause ()
BOOL BASSDEF() BASS_SetVolume (float volume)
float BASSDEF() BASS_GetVolume ()
HPLUGIN BASSDEF() BASS_PluginLoad (const char *file, DWORD flags)
BOOL BASSDEF() BASS_PluginFree (HPLUGIN handle)
const BASS_PLUGININFO *BASSDEF() BASS_PluginGetInfo (HPLUGIN handle)
BOOL BASSDEF() BASS_Set3DFactors (float distf, float rollf, float doppf)
BOOL BASSDEF() BASS_Get3DFactors (float *distf, float *rollf, float *doppf)
BOOL BASSDEF() BASS_Set3DPosition (const BASS_3DVECTOR *pos, const BASS_3DVECTOR *vel, const BASS_3DVECTOR *front, const BASS_3DVECTOR *top)
BOOL BASSDEF() BASS_Get3DPosition (BASS_3DVECTOR *pos, BASS_3DVECTOR *vel, BASS_3DVECTOR *front, BASS_3DVECTOR *top)
void BASSDEF() BASS_Apply3D ()
HMUSIC BASSDEF() BASS_MusicLoad (BOOL mem, const void *file, QWORD offset, DWORD length, DWORD flags, DWORD freq)
BOOL BASSDEF() BASS_MusicFree (HMUSIC handle)
HSAMPLE BASSDEF() BASS_SampleLoad (BOOL mem, const void *file, QWORD offset, DWORD length, DWORD max, DWORD flags)
HSAMPLE BASSDEF() BASS_SampleCreate (DWORD length, DWORD freq, DWORD chans, DWORD max, DWORD flags)
BOOL BASSDEF() BASS_SampleFree (HSAMPLE handle)
BOOL BASSDEF() BASS_SampleSetData (HSAMPLE handle, const void *buffer)
BOOL BASSDEF() BASS_SampleGetData (HSAMPLE handle, void *buffer)
BOOL BASSDEF() BASS_SampleGetInfo (HSAMPLE handle, BASS_SAMPLE *info)
BOOL BASSDEF() BASS_SampleSetInfo (HSAMPLE handle, const BASS_SAMPLE *info)
HCHANNEL BASSDEF() BASS_SampleGetChannel (HSAMPLE handle, BOOL onlynew)
DWORD BASSDEF() BASS_SampleGetChannels (HSAMPLE handle, HCHANNEL *channels)
BOOL BASSDEF() BASS_SampleStop (HSAMPLE handle)
HSTREAM BASSDEF() BASS_StreamCreate (DWORD freq, DWORD chans, DWORD flags, STREAMPROC *proc, void *user)
HSTREAM BASSDEF() BASS_StreamCreateFile (BOOL mem, const void *file, QWORD offset, QWORD length, DWORD flags)
HSTREAM BASSDEF() BASS_StreamCreateURL (const char *url, DWORD offset, DWORD flags, DOWNLOADPROC *proc, void *user)
HSTREAM BASSDEF() BASS_StreamCreateFileUser (DWORD system, DWORD flags, const BASS_FILEPROCS *proc, void *user)
BOOL BASSDEF() BASS_StreamFree (HSTREAM handle)
QWORD BASSDEF() BASS_StreamGetFilePosition (HSTREAM handle, DWORD mode)
DWORD BASSDEF() BASS_StreamPutData (HSTREAM handle, const void *buffer, DWORD length)
DWORD BASSDEF() BASS_StreamPutFileData (HSTREAM handle, const void *buffer, DWORD length)
BOOL BASSDEF() BASS_RecordGetDeviceInfo (DWORD device, BASS_DEVICEINFO *info)
BOOL BASSDEF() BASS_RecordInit (int device)
BOOL BASSDEF() BASS_RecordSetDevice (DWORD device)
DWORD BASSDEF() BASS_RecordGetDevice ()
BOOL BASSDEF() BASS_RecordFree ()
BOOL BASSDEF() BASS_RecordGetInfo (BASS_RECORDINFO *info)
const char *BASSDEF() BASS_RecordGetInputName (int input)
BOOL BASSDEF() BASS_RecordSetInput (int input, DWORD flags, float volume)
DWORD BASSDEF() BASS_RecordGetInput (int input, float *volume)
HRECORD BASSDEF() BASS_RecordStart (DWORD freq, DWORD chans, DWORD flags, RECORDPROC *proc, void *user)
double BASSDEF() BASS_ChannelBytes2Seconds (DWORD handle, QWORD pos)
QWORD BASSDEF() BASS_ChannelSeconds2Bytes (DWORD handle, double pos)
DWORD BASSDEF() BASS_ChannelGetDevice (DWORD handle)
BOOL BASSDEF() BASS_ChannelSetDevice (DWORD handle, DWORD device)
DWORD BASSDEF() BASS_ChannelIsActive (DWORD handle)
BOOL BASSDEF() BASS_ChannelGetInfo (DWORD handle, BASS_CHANNELINFO *info)
const char *BASSDEF() BASS_ChannelGetTags (DWORD handle, DWORD tags)
DWORD BASSDEF() BASS_ChannelFlags (DWORD handle, DWORD flags, DWORD mask)
BOOL BASSDEF() BASS_ChannelUpdate (DWORD handle, DWORD length)
BOOL BASSDEF() BASS_ChannelLock (DWORD handle, BOOL lock)
BOOL BASSDEF() BASS_ChannelPlay (DWORD handle, BOOL restart)
BOOL BASSDEF() BASS_ChannelStop (DWORD handle)
BOOL BASSDEF() BASS_ChannelPause (DWORD handle)
BOOL BASSDEF() BASS_ChannelSetAttribute (DWORD handle, DWORD attrib, float value)
BOOL BASSDEF() BASS_ChannelGetAttribute (DWORD handle, DWORD attrib, float *value)
BOOL BASSDEF() BASS_ChannelSlideAttribute (DWORD handle, DWORD attrib, float value, DWORD time)
BOOL BASSDEF() BASS_ChannelIsSliding (DWORD handle, DWORD attrib)
BOOL BASSDEF() BASS_ChannelSetAttributeEx (DWORD handle, DWORD attrib, void *value, DWORD size)
DWORD BASSDEF() BASS_ChannelGetAttributeEx (DWORD handle, DWORD attrib, void *value, DWORD size)
BOOL BASSDEF() BASS_ChannelSet3DAttributes (DWORD handle, int mode, float min, float max, int iangle, int oangle, float outvol)
BOOL BASSDEF() BASS_ChannelGet3DAttributes (DWORD handle, DWORD *mode, float *min, float *max, DWORD *iangle, DWORD *oangle, float *outvol)
BOOL BASSDEF() BASS_ChannelSet3DPosition (DWORD handle, const BASS_3DVECTOR *pos, const BASS_3DVECTOR *orient, const BASS_3DVECTOR *vel)
BOOL BASSDEF() BASS_ChannelGet3DPosition (DWORD handle, BASS_3DVECTOR *pos, BASS_3DVECTOR *orient, BASS_3DVECTOR *vel)
QWORD BASSDEF() BASS_ChannelGetLength (DWORD handle, DWORD mode)
BOOL BASSDEF() BASS_ChannelSetPosition (DWORD handle, QWORD pos, DWORD mode)
QWORD BASSDEF() BASS_ChannelGetPosition (DWORD handle, DWORD mode)
DWORD BASSDEF() BASS_ChannelGetLevel (DWORD handle)
BOOL BASSDEF() BASS_ChannelGetLevelEx (DWORD handle, float *levels, float length, DWORD flags)
DWORD BASSDEF() BASS_ChannelGetData (DWORD handle, void *buffer, DWORD length)
HSYNC BASSDEF() BASS_ChannelSetSync (DWORD handle, DWORD type, QWORD param, SYNCPROC *proc, void *user)
BOOL BASSDEF() BASS_ChannelRemoveSync (DWORD handle, HSYNC sync)
HDSP BASSDEF() BASS_ChannelSetDSP (DWORD handle, DSPPROC *proc, void *user, int priority)
BOOL BASSDEF() BASS_ChannelRemoveDSP (DWORD handle, HDSP dsp)
BOOL BASSDEF() BASS_ChannelSetLink (DWORD handle, DWORD chan)
BOOL BASSDEF() BASS_ChannelRemoveLink (DWORD handle, DWORD chan)
HFX BASSDEF() BASS_ChannelSetFX (DWORD handle, DWORD type, int priority)
BOOL BASSDEF() BASS_ChannelRemoveFX (DWORD handle, HFX fx)
BOOL BASSDEF() BASS_FXSetParameters (HFX handle, const void *params)
BOOL BASSDEF() BASS_FXGetParameters (HFX handle, void *params)
BOOL BASSDEF() BASS_FXReset (HFX handle)
BOOL BASSDEF() BASS_FXSetPriority (HFX handle, int priority)
Macro Definition Documentation
_WAVEFORMATEX_
#define _WAVEFORMATEX_
BASS_3DALG_DEFAULT
#define BASS_3DALG_DEFAULT 0
BASS_3DALG_FULL
#define BASS_3DALG_FULL 2
BASS_3DALG_LIGHT
#define BASS_3DALG_LIGHT 3
BASS_3DALG_OFF
#define BASS_3DALG_OFF 1
BASS_3DMODE_NORMAL
#define BASS_3DMODE_NORMAL 0
BASS_3DMODE_OFF
#define BASS_3DMODE_OFF 2
BASS_3DMODE_RELATIVE
#define BASS_3DMODE_RELATIVE 1
BASS_ACTIVE_PAUSED
#define BASS_ACTIVE_PAUSED 3
BASS_ACTIVE_PLAYING
#define BASS_ACTIVE_PLAYING 1
BASS_ACTIVE_STALLED
#define BASS_ACTIVE_STALLED 2
BASS_ACTIVE_STOPPED
#define BASS_ACTIVE_STOPPED 0
BASS_ASYNCFILE
#define BASS_ASYNCFILE 0x40000000
BASS_ATTRIB_BITRATE
#define BASS_ATTRIB_BITRATE 12
BASS_ATTRIB_BUFFER
#define BASS_ATTRIB_BUFFER 13
BASS_ATTRIB_CPU
#define BASS_ATTRIB_CPU 7
BASS_ATTRIB_EAXMIX
#define BASS_ATTRIB_EAXMIX 4
BASS_ATTRIB_FREQ
#define BASS_ATTRIB_FREQ 1
BASS_ATTRIB_MUSIC_ACTIVE
#define BASS_ATTRIB_MUSIC_ACTIVE 0x106
BASS_ATTRIB_MUSIC_AMPLIFY
#define BASS_ATTRIB_MUSIC_AMPLIFY 0x100
BASS_ATTRIB_MUSIC_BPM
#define BASS_ATTRIB_MUSIC_BPM 0x103
BASS_ATTRIB_MUSIC_PANSEP
#define BASS_ATTRIB_MUSIC_PANSEP 0x101
BASS_ATTRIB_MUSIC_PSCALER
#define BASS_ATTRIB_MUSIC_PSCALER 0x102
BASS_ATTRIB_MUSIC_SPEED
#define BASS_ATTRIB_MUSIC_SPEED 0x104
BASS_ATTRIB_MUSIC_VOL_CHAN
#define BASS_ATTRIB_MUSIC_VOL_CHAN 0x200
BASS_ATTRIB_MUSIC_VOL_GLOBAL
#define BASS_ATTRIB_MUSIC_VOL_GLOBAL 0x105
BASS_ATTRIB_MUSIC_VOL_INST
#define BASS_ATTRIB_MUSIC_VOL_INST 0x300
BASS_ATTRIB_NET_RESUME
#define BASS_ATTRIB_NET_RESUME 9
BASS_ATTRIB_NOBUFFER
#define BASS_ATTRIB_NOBUFFER 5
BASS_ATTRIB_NORAMP
#define BASS_ATTRIB_NORAMP 11
BASS_ATTRIB_PAN
#define BASS_ATTRIB_PAN 3
BASS_ATTRIB_SCANINFO
#define BASS_ATTRIB_SCANINFO 10
BASS_ATTRIB_SRC
#define BASS_ATTRIB_SRC 8
BASS_ATTRIB_VBR
#define BASS_ATTRIB_VBR 6
BASS_ATTRIB_VOL
#define BASS_ATTRIB_VOL 2
BASS_CONFIG_3DALGORITHM
#define BASS_CONFIG_3DALGORITHM 10
BASS_CONFIG_AIRPLAY
#define BASS_CONFIG_AIRPLAY 49
BASS_CONFIG_AM_DISABLE
#define BASS_CONFIG_AM_DISABLE 58
BASS_CONFIG_ASYNCFILE_BUFFER
#define BASS_CONFIG_ASYNCFILE_BUFFER 45
BASS_CONFIG_BUFFER
#define BASS_CONFIG_BUFFER 0
BASS_CONFIG_CURVE_PAN
#define BASS_CONFIG_CURVE_PAN 8
BASS_CONFIG_CURVE_VOL
#define BASS_CONFIG_CURVE_VOL 7
BASS_CONFIG_DEV_BUFFER
#define BASS_CONFIG_DEV_BUFFER 27
BASS_CONFIG_DEV_DEFAULT
#define BASS_CONFIG_DEV_DEFAULT 36
BASS_CONFIG_DEV_NONSTOP
#define BASS_CONFIG_DEV_NONSTOP 50
BASS_CONFIG_DEV_PERIOD
#define BASS_CONFIG_DEV_PERIOD 53
BASS_CONFIG_FLOAT
#define BASS_CONFIG_FLOAT 54
BASS_CONFIG_FLOATDSP
#define BASS_CONFIG_FLOATDSP 9
BASS_CONFIG_GVOL_MUSIC
#define BASS_CONFIG_GVOL_MUSIC 6
BASS_CONFIG_GVOL_SAMPLE
#define BASS_CONFIG_GVOL_SAMPLE 4
BASS_CONFIG_GVOL_STREAM
#define BASS_CONFIG_GVOL_STREAM 5
BASS_CONFIG_HANDLES
#define BASS_CONFIG_HANDLES 41
BASS_CONFIG_IOS_MIXAUDIO
#define BASS_CONFIG_IOS_MIXAUDIO 34
BASS_CONFIG_IOS_NOCATEGORY
#define BASS_CONFIG_IOS_NOCATEGORY 51
BASS_CONFIG_IOS_NOTIFY
#define BASS_CONFIG_IOS_NOTIFY 46
BASS_CONFIG_IOS_SPEAKER
#define BASS_CONFIG_IOS_SPEAKER 39
BASS_CONFIG_MF_DISABLE
#define BASS_CONFIG_MF_DISABLE 40
BASS_CONFIG_MF_VIDEO
#define BASS_CONFIG_MF_VIDEO 48
BASS_CONFIG_MUSIC_VIRTUAL
#define BASS_CONFIG_MUSIC_VIRTUAL 22
BASS_CONFIG_NET_AGENT
#define BASS_CONFIG_NET_AGENT 16
BASS_CONFIG_NET_BUFFER
#define BASS_CONFIG_NET_BUFFER 12
BASS_CONFIG_NET_PASSIVE
#define BASS_CONFIG_NET_PASSIVE 18
BASS_CONFIG_NET_PLAYLIST
#define BASS_CONFIG_NET_PLAYLIST 21
BASS_CONFIG_NET_PLAYLIST_DEPTH
#define BASS_CONFIG_NET_PLAYLIST_DEPTH 59
BASS_CONFIG_NET_PREBUF
#define BASS_CONFIG_NET_PREBUF 15
BASS_CONFIG_NET_PREBUF_WAIT
#define BASS_CONFIG_NET_PREBUF_WAIT 60
BASS_CONFIG_NET_PROXY
#define BASS_CONFIG_NET_PROXY 17
BASS_CONFIG_NET_READTIMEOUT
#define BASS_CONFIG_NET_READTIMEOUT 37
BASS_CONFIG_NET_SEEK
#define BASS_CONFIG_NET_SEEK 56
BASS_CONFIG_NET_TIMEOUT
#define BASS_CONFIG_NET_TIMEOUT 11
BASS_CONFIG_OGG_PRESCAN
#define BASS_CONFIG_OGG_PRESCAN 47
BASS_CONFIG_PAUSE_NOPLAY
#define BASS_CONFIG_PAUSE_NOPLAY 13
BASS_CONFIG_REC_BUFFER
#define BASS_CONFIG_REC_BUFFER 19
BASS_CONFIG_SRC
#define BASS_CONFIG_SRC 43
BASS_CONFIG_SRC_SAMPLE
#define BASS_CONFIG_SRC_SAMPLE 44
BASS_CONFIG_UNICODE
#define BASS_CONFIG_UNICODE 42
BASS_CONFIG_UPDATEPERIOD
#define BASS_CONFIG_UPDATEPERIOD 1
BASS_CONFIG_UPDATETHREADS
#define BASS_CONFIG_UPDATETHREADS 24
BASS_CONFIG_VERIFY
#define BASS_CONFIG_VERIFY 23
BASS_CONFIG_VERIFY_NET
#define BASS_CONFIG_VERIFY_NET 52
BASS_CONFIG_VISTA_SPEAKERS
#define BASS_CONFIG_VISTA_SPEAKERS 38
BASS_CONFIG_VISTA_TRUEPOS
#define BASS_CONFIG_VISTA_TRUEPOS 30
BASS_CTYPE_MUSIC_IT
#define BASS_CTYPE_MUSIC_IT 0x20004
BASS_CTYPE_MUSIC_MO3
#define BASS_CTYPE_MUSIC_MO3 0x00100
BASS_CTYPE_MUSIC_MOD
#define BASS_CTYPE_MUSIC_MOD 0x20000
BASS_CTYPE_MUSIC_MTM
#define BASS_CTYPE_MUSIC_MTM 0x20001
BASS_CTYPE_MUSIC_S3M
#define BASS_CTYPE_MUSIC_S3M 0x20002
BASS_CTYPE_MUSIC_XM
#define BASS_CTYPE_MUSIC_XM 0x20003
BASS_CTYPE_RECORD
#define BASS_CTYPE_RECORD 2
BASS_CTYPE_SAMPLE
#define BASS_CTYPE_SAMPLE 1
BASS_CTYPE_STREAM
#define BASS_CTYPE_STREAM 0x10000
BASS_CTYPE_STREAM_AIFF
#define BASS_CTYPE_STREAM_AIFF 0x10006
BASS_CTYPE_STREAM_AM
#define BASS_CTYPE_STREAM_AM 0x10009
BASS_CTYPE_STREAM_CA
#define BASS_CTYPE_STREAM_CA 0x10007
BASS_CTYPE_STREAM_DEVICE
#define BASS_CTYPE_STREAM_DEVICE 0x18001
BASS_CTYPE_STREAM_DUMMY
#define BASS_CTYPE_STREAM_DUMMY 0x18000
BASS_CTYPE_STREAM_MF
#define BASS_CTYPE_STREAM_MF 0x10008
BASS_CTYPE_STREAM_MP1
#define BASS_CTYPE_STREAM_MP1 0x10003
BASS_CTYPE_STREAM_MP2
#define BASS_CTYPE_STREAM_MP2 0x10004
BASS_CTYPE_STREAM_MP3
#define BASS_CTYPE_STREAM_MP3 0x10005
BASS_CTYPE_STREAM_OGG
#define BASS_CTYPE_STREAM_OGG 0x10002
BASS_CTYPE_STREAM_WAV
#define BASS_CTYPE_STREAM_WAV 0x40000
BASS_CTYPE_STREAM_WAV_FLOAT
#define BASS_CTYPE_STREAM_WAV_FLOAT 0x50003
BASS_CTYPE_STREAM_WAV_PCM
#define BASS_CTYPE_STREAM_WAV_PCM 0x50001
BASS_DATA_AVAILABLE
#define BASS_DATA_AVAILABLE 0
BASS_DATA_FFT1024
#define BASS_DATA_FFT1024 0x80000002
BASS_DATA_FFT16384
#define BASS_DATA_FFT16384 0x80000006
BASS_DATA_FFT2048
#define BASS_DATA_FFT2048 0x80000003
BASS_DATA_FFT256
#define BASS_DATA_FFT256 0x80000000
BASS_DATA_FFT32768
#define BASS_DATA_FFT32768 0x80000007
BASS_DATA_FFT4096
#define BASS_DATA_FFT4096 0x80000004
BASS_DATA_FFT512
#define BASS_DATA_FFT512 0x80000001
BASS_DATA_FFT8192
#define BASS_DATA_FFT8192 0x80000005
BASS_DATA_FFT_COMPLEX
#define BASS_DATA_FFT_COMPLEX 0x80
BASS_DATA_FFT_INDIVIDUAL
#define BASS_DATA_FFT_INDIVIDUAL 0x10
BASS_DATA_FFT_NOWINDOW
#define BASS_DATA_FFT_NOWINDOW 0x20
BASS_DATA_FFT_REMOVEDC
#define BASS_DATA_FFT_REMOVEDC 0x40
BASS_DATA_FIXED
#define BASS_DATA_FIXED 0x20000000
BASS_DATA_FLOAT
#define BASS_DATA_FLOAT 0x40000000
BASS_DEVICE_16BITS
#define BASS_DEVICE_16BITS 8
BASS_DEVICE_3D
#define BASS_DEVICE_3D 4
BASS_DEVICE_8BITS
#define BASS_DEVICE_8BITS 1
BASS_DEVICE_AUDIOTRACK
#define BASS_DEVICE_AUDIOTRACK 0x20000
BASS_DEVICE_CPSPEAKERS
#define BASS_DEVICE_CPSPEAKERS 0x400
BASS_DEVICE_DEFAULT
#define BASS_DEVICE_DEFAULT 2
BASS_DEVICE_DMIX
#define BASS_DEVICE_DMIX 0x2000
BASS_DEVICE_DSOUND
#define BASS_DEVICE_DSOUND 0x40000
BASS_DEVICE_ENABLED
#define BASS_DEVICE_ENABLED 1
BASS_DEVICE_FREQ
#define BASS_DEVICE_FREQ 0x4000
BASS_DEVICE_HOG
#define BASS_DEVICE_HOG 0x10000
BASS_DEVICE_INIT
#define BASS_DEVICE_INIT 4
BASS_DEVICE_LATENCY
#define BASS_DEVICE_LATENCY 0x100
BASS_DEVICE_LOOPBACK
#define BASS_DEVICE_LOOPBACK 8
BASS_DEVICE_MONO
#define BASS_DEVICE_MONO 2
BASS_DEVICE_NOSPEAKER
#define BASS_DEVICE_NOSPEAKER 0x1000
BASS_DEVICE_SPEAKERS
#define BASS_DEVICE_SPEAKERS 0x800
BASS_DEVICE_STEREO
#define BASS_DEVICE_STEREO 0x8000
BASS_DEVICE_TYPE_DIGITAL
#define BASS_DEVICE_TYPE_DIGITAL 0x08000000
BASS_DEVICE_TYPE_DISPLAYPORT
#define BASS_DEVICE_TYPE_DISPLAYPORT 0x40000000
BASS_DEVICE_TYPE_HANDSET
#define BASS_DEVICE_TYPE_HANDSET 0x07000000
BASS_DEVICE_TYPE_HDMI
#define BASS_DEVICE_TYPE_HDMI 0x0a000000
BASS_DEVICE_TYPE_HEADPHONES
#define BASS_DEVICE_TYPE_HEADPHONES 0x04000000
BASS_DEVICE_TYPE_HEADSET
#define BASS_DEVICE_TYPE_HEADSET 0x06000000
BASS_DEVICE_TYPE_LINE
#define BASS_DEVICE_TYPE_LINE 0x03000000
BASS_DEVICE_TYPE_MASK
#define BASS_DEVICE_TYPE_MASK 0xff000000
BASS_DEVICE_TYPE_MICROPHONE
#define BASS_DEVICE_TYPE_MICROPHONE 0x05000000
BASS_DEVICE_TYPE_NETWORK
#define BASS_DEVICE_TYPE_NETWORK 0x01000000
BASS_DEVICE_TYPE_SPDIF
#define BASS_DEVICE_TYPE_SPDIF 0x09000000
BASS_DEVICE_TYPE_SPEAKERS
#define BASS_DEVICE_TYPE_SPEAKERS 0x02000000
BASS_DEVICES_AIRPLAY
#define BASS_DEVICES_AIRPLAY 0x1000000
BASS_DX8_PHASE_180
#define BASS_DX8_PHASE_180 4
BASS_DX8_PHASE_90
#define BASS_DX8_PHASE_90 3
BASS_DX8_PHASE_NEG_180
#define BASS_DX8_PHASE_NEG_180 0
BASS_DX8_PHASE_NEG_90
#define BASS_DX8_PHASE_NEG_90 1
BASS_DX8_PHASE_ZERO
#define BASS_DX8_PHASE_ZERO 2
BASS_ERROR_ALREADY
#define BASS_ERROR_ALREADY 14
BASS_ERROR_BUFLOST
#define BASS_ERROR_BUFLOST 4
BASS_ERROR_BUSY
#define BASS_ERROR_BUSY 46
BASS_ERROR_CODEC
#define BASS_ERROR_CODEC 44
BASS_ERROR_CREATE
#define BASS_ERROR_CREATE 33
BASS_ERROR_DECODE
#define BASS_ERROR_DECODE 38
BASS_ERROR_DEVICE
#define BASS_ERROR_DEVICE 23
BASS_ERROR_DRIVER
#define BASS_ERROR_DRIVER 3
BASS_ERROR_DX
#define BASS_ERROR_DX 39
BASS_ERROR_EMPTY
#define BASS_ERROR_EMPTY 31
BASS_ERROR_ENDED
#define BASS_ERROR_ENDED 45
BASS_ERROR_FILEFORM
#define BASS_ERROR_FILEFORM 41
BASS_ERROR_FILEOPEN
#define BASS_ERROR_FILEOPEN 2
BASS_ERROR_FORMAT
#define BASS_ERROR_FORMAT 6
BASS_ERROR_FREQ
#define BASS_ERROR_FREQ 25
BASS_ERROR_HANDLE
#define BASS_ERROR_HANDLE 5
BASS_ERROR_ILLPARAM
#define BASS_ERROR_ILLPARAM 20
BASS_ERROR_ILLTYPE
#define BASS_ERROR_ILLTYPE 19
BASS_ERROR_INIT
#define BASS_ERROR_INIT 8
BASS_ERROR_MEM
#define BASS_ERROR_MEM 1
BASS_ERROR_NO3D
#define BASS_ERROR_NO3D 21
BASS_ERROR_NOCHAN
#define BASS_ERROR_NOCHAN 18
BASS_ERROR_NOEAX
#define BASS_ERROR_NOEAX 22
BASS_ERROR_NOFX
#define BASS_ERROR_NOFX 34
BASS_ERROR_NOHW
#define BASS_ERROR_NOHW 29
BASS_ERROR_NONET
#define BASS_ERROR_NONET 32
BASS_ERROR_NOPLAY
#define BASS_ERROR_NOPLAY 24
BASS_ERROR_NOTAVAIL
#define BASS_ERROR_NOTAVAIL 37
BASS_ERROR_NOTFILE
#define BASS_ERROR_NOTFILE 27
BASS_ERROR_POSITION
#define BASS_ERROR_POSITION 7
BASS_ERROR_SPEAKER
#define BASS_ERROR_SPEAKER 42
BASS_ERROR_SSL
#define BASS_ERROR_SSL 10
BASS_ERROR_START
#define BASS_ERROR_START 9
BASS_ERROR_TIMEOUT
#define BASS_ERROR_TIMEOUT 40
BASS_ERROR_UNKNOWN
#define BASS_ERROR_UNKNOWN -1
BASS_ERROR_VERSION
#define BASS_ERROR_VERSION 43
BASS_FILEDATA_END
#define BASS_FILEDATA_END 0
BASS_FILEPOS_ASYNCBUF
#define BASS_FILEPOS_ASYNCBUF 7
BASS_FILEPOS_BUFFER
#define BASS_FILEPOS_BUFFER 5
BASS_FILEPOS_BUFFERING
#define BASS_FILEPOS_BUFFERING 9
BASS_FILEPOS_CONNECTED
#define BASS_FILEPOS_CONNECTED 4
BASS_FILEPOS_CURRENT
#define BASS_FILEPOS_CURRENT 0
BASS_FILEPOS_DECODE
#define BASS_FILEPOS_DECODE BASS_FILEPOS_CURRENT
BASS_FILEPOS_DOWNLOAD
#define BASS_FILEPOS_DOWNLOAD 1
BASS_FILEPOS_END
#define BASS_FILEPOS_END 2
BASS_FILEPOS_SIZE
#define BASS_FILEPOS_SIZE 8
BASS_FILEPOS_SOCKET
#define BASS_FILEPOS_SOCKET 6
BASS_FILEPOS_START
#define BASS_FILEPOS_START 3
BASS_FX_DX8_CHORUS
#define BASS_FX_DX8_CHORUS 0
BASS_FX_DX8_COMPRESSOR
#define BASS_FX_DX8_COMPRESSOR 1
BASS_FX_DX8_DISTORTION
#define BASS_FX_DX8_DISTORTION 2
BASS_FX_DX8_ECHO
#define BASS_FX_DX8_ECHO 3
BASS_FX_DX8_FLANGER
#define BASS_FX_DX8_FLANGER 4
BASS_FX_DX8_GARGLE
#define BASS_FX_DX8_GARGLE 5
BASS_FX_DX8_I3DL2REVERB
#define BASS_FX_DX8_I3DL2REVERB 6
BASS_FX_DX8_PARAMEQ
#define BASS_FX_DX8_PARAMEQ 7
BASS_FX_DX8_REVERB
#define BASS_FX_DX8_REVERB 8
BASS_FX_VOLUME
#define BASS_FX_VOLUME 9
BASS_INPUT_OFF
#define BASS_INPUT_OFF 0x10000
BASS_INPUT_ON
#define BASS_INPUT_ON 0x20000
BASS_INPUT_TYPE_ANALOG
#define BASS_INPUT_TYPE_ANALOG 0x0a000000
BASS_INPUT_TYPE_AUX
#define BASS_INPUT_TYPE_AUX 0x09000000
BASS_INPUT_TYPE_CD
#define BASS_INPUT_TYPE_CD 0x05000000
BASS_INPUT_TYPE_DIGITAL
#define BASS_INPUT_TYPE_DIGITAL 0x01000000
BASS_INPUT_TYPE_LINE
#define BASS_INPUT_TYPE_LINE 0x02000000
BASS_INPUT_TYPE_MASK
#define BASS_INPUT_TYPE_MASK 0xff000000
BASS_INPUT_TYPE_MIC
#define BASS_INPUT_TYPE_MIC 0x03000000
BASS_INPUT_TYPE_PHONE
#define BASS_INPUT_TYPE_PHONE 0x06000000
BASS_INPUT_TYPE_SPEAKER
#define BASS_INPUT_TYPE_SPEAKER 0x07000000
BASS_INPUT_TYPE_SYNTH
#define BASS_INPUT_TYPE_SYNTH 0x04000000
BASS_INPUT_TYPE_UNDEF
#define BASS_INPUT_TYPE_UNDEF 0x00000000
BASS_INPUT_TYPE_WAVE
#define BASS_INPUT_TYPE_WAVE 0x08000000
BASS_IOSNOTIFY_INTERRUPT
#define BASS_IOSNOTIFY_INTERRUPT 1
BASS_IOSNOTIFY_INTERRUPT_END
#define BASS_IOSNOTIFY_INTERRUPT_END 2
BASS_LEVEL_MONO
#define BASS_LEVEL_MONO 1
BASS_LEVEL_RMS
#define BASS_LEVEL_RMS 4
BASS_LEVEL_STEREO
#define BASS_LEVEL_STEREO 2
BASS_LEVEL_VOLPAN
#define BASS_LEVEL_VOLPAN 8
BASS_MP3_IGNOREDELAY
#define BASS_MP3_IGNOREDELAY 0x200
BASS_MP3_SETPOS
#define BASS_MP3_SETPOS BASS_STREAM_PRESCAN
BASS_MUSIC_3D
#define BASS_MUSIC_3D BASS_SAMPLE_3D
BASS_MUSIC_AUTOFREE
#define BASS_MUSIC_AUTOFREE BASS_STREAM_AUTOFREE
BASS_MUSIC_CALCLEN
#define BASS_MUSIC_CALCLEN BASS_MUSIC_PRESCAN
BASS_MUSIC_DECODE
#define BASS_MUSIC_DECODE BASS_STREAM_DECODE
BASS_MUSIC_FLOAT
#define BASS_MUSIC_FLOAT BASS_SAMPLE_FLOAT
BASS_MUSIC_FT2MOD
#define BASS_MUSIC_FT2MOD 0x2000
BASS_MUSIC_FT2PAN
#define BASS_MUSIC_FT2PAN 0x2000
BASS_MUSIC_FX
#define BASS_MUSIC_FX BASS_SAMPLE_FX
BASS_MUSIC_LOOP
#define BASS_MUSIC_LOOP BASS_SAMPLE_LOOP
BASS_MUSIC_MONO
#define BASS_MUSIC_MONO BASS_SAMPLE_MONO
BASS_MUSIC_NONINTER
#define BASS_MUSIC_NONINTER 0x10000
BASS_MUSIC_NOSAMPLE
#define BASS_MUSIC_NOSAMPLE 0x100000
BASS_MUSIC_POSRESET
#define BASS_MUSIC_POSRESET 0x8000
BASS_MUSIC_POSRESETEX
#define BASS_MUSIC_POSRESETEX 0x400000
BASS_MUSIC_PRESCAN
#define BASS_MUSIC_PRESCAN BASS_STREAM_PRESCAN
BASS_MUSIC_PT1MOD
#define BASS_MUSIC_PT1MOD 0x4000
BASS_MUSIC_RAMP
#define BASS_MUSIC_RAMP 0x200
BASS_MUSIC_RAMPS
#define BASS_MUSIC_RAMPS 0x400
BASS_MUSIC_SINCINTER
#define BASS_MUSIC_SINCINTER 0x800000
BASS_MUSIC_STOPBACK
#define BASS_MUSIC_STOPBACK 0x80000
BASS_MUSIC_SURROUND
#define BASS_MUSIC_SURROUND 0x800
BASS_MUSIC_SURROUND2
#define BASS_MUSIC_SURROUND2 0x1000
BASS_NODEVICE
#define BASS_NODEVICE 0x20000
BASS_OBJECT_DS
#define BASS_OBJECT_DS 1
BASS_OBJECT_DS3DL
#define BASS_OBJECT_DS3DL 2
BASS_OK
#define BASS_OK 0
BASS_ORIGRES_FLOAT
#define BASS_ORIGRES_FLOAT 0x10000
BASS_POS_BYTE
#define BASS_POS_BYTE 0
BASS_POS_DECODE
#define BASS_POS_DECODE 0x10000000
BASS_POS_DECODETO
#define BASS_POS_DECODETO 0x20000000
BASS_POS_INEXACT
#define BASS_POS_INEXACT 0x8000000
BASS_POS_MUSIC_ORDER
#define BASS_POS_MUSIC_ORDER 1
BASS_POS_OGG
#define BASS_POS_OGG 3
BASS_POS_RELATIVE
#define BASS_POS_RELATIVE 0x4000000
BASS_POS_RESET
#define BASS_POS_RESET 0x2000000
BASS_POS_SCAN
#define BASS_POS_SCAN 0x40000000
BASS_RECORD_AGC
#define BASS_RECORD_AGC 0x4000
BASS_RECORD_ECHOCANCEL
#define BASS_RECORD_ECHOCANCEL 0x2000
BASS_RECORD_PAUSE
#define BASS_RECORD_PAUSE 0x8000
BASS_SAMPLE_3D
#define BASS_SAMPLE_3D 8
BASS_SAMPLE_8BITS
#define BASS_SAMPLE_8BITS 1
BASS_SAMPLE_FLOAT
#define BASS_SAMPLE_FLOAT 256
BASS_SAMPLE_FX
#define BASS_SAMPLE_FX 128
BASS_SAMPLE_LOOP
#define BASS_SAMPLE_LOOP 4
BASS_SAMPLE_MONO
#define BASS_SAMPLE_MONO 2
BASS_SAMPLE_MUTEMAX
#define BASS_SAMPLE_MUTEMAX 32
BASS_SAMPLE_OVER_DIST
#define BASS_SAMPLE_OVER_DIST 0x30000
BASS_SAMPLE_OVER_POS
#define BASS_SAMPLE_OVER_POS 0x20000
BASS_SAMPLE_OVER_VOL
#define BASS_SAMPLE_OVER_VOL 0x10000
BASS_SAMPLE_SOFTWARE
#define BASS_SAMPLE_SOFTWARE 16
BASS_SAMPLE_VAM
#define BASS_SAMPLE_VAM 64
BASS_SLIDE_LOG
#define BASS_SLIDE_LOG 0x1000000
BASS_SPEAKER_CENLFE
#define BASS_SPEAKER_CENLFE 0x3000000
BASS_SPEAKER_CENTER
#define BASS_SPEAKER_CENTER BASS_SPEAKER_CENLFE|BASS_SPEAKER_LEFT
BASS_SPEAKER_FRONT
#define BASS_SPEAKER_FRONT 0x1000000
BASS_SPEAKER_FRONTLEFT
#define BASS_SPEAKER_FRONTLEFT BASS_SPEAKER_FRONT|BASS_SPEAKER_LEFT
BASS_SPEAKER_FRONTRIGHT
#define BASS_SPEAKER_FRONTRIGHT BASS_SPEAKER_FRONT|BASS_SPEAKER_RIGHT
BASS_SPEAKER_LEFT
#define BASS_SPEAKER_LEFT 0x10000000
BASS_SPEAKER_LFE
#define BASS_SPEAKER_LFE BASS_SPEAKER_CENLFE|BASS_SPEAKER_RIGHT
BASS_SPEAKER_N
#define BASS_SPEAKER_N (n) ((n)<<24)
BASS_SPEAKER_REAR
#define BASS_SPEAKER_REAR 0x2000000
BASS_SPEAKER_REAR2
#define BASS_SPEAKER_REAR2 0x4000000
BASS_SPEAKER_REAR2LEFT
#define BASS_SPEAKER_REAR2LEFT BASS_SPEAKER_REAR2|BASS_SPEAKER_LEFT
BASS_SPEAKER_REAR2RIGHT
#define BASS_SPEAKER_REAR2RIGHT BASS_SPEAKER_REAR2|BASS_SPEAKER_RIGHT
BASS_SPEAKER_REARLEFT
#define BASS_SPEAKER_REARLEFT BASS_SPEAKER_REAR|BASS_SPEAKER_LEFT
BASS_SPEAKER_REARRIGHT
#define BASS_SPEAKER_REARRIGHT BASS_SPEAKER_REAR|BASS_SPEAKER_RIGHT
BASS_SPEAKER_RIGHT
#define BASS_SPEAKER_RIGHT 0x20000000
BASS_STREAM_AUTOFREE
#define BASS_STREAM_AUTOFREE 0x40000
BASS_STREAM_BLOCK
#define BASS_STREAM_BLOCK 0x100000
BASS_STREAM_DECODE
#define BASS_STREAM_DECODE 0x200000
BASS_STREAM_PRESCAN
#define BASS_STREAM_PRESCAN 0x20000
BASS_STREAM_RESTRATE
#define BASS_STREAM_RESTRATE 0x80000
BASS_STREAM_STATUS
#define BASS_STREAM_STATUS 0x800000
BASS_STREAMPROC_END
#define BASS_STREAMPROC_END 0x80000000
BASS_SYNC_DOWNLOAD
#define BASS_SYNC_DOWNLOAD 7
BASS_SYNC_END
#define BASS_SYNC_END 2
BASS_SYNC_FREE
#define BASS_SYNC_FREE 8
BASS_SYNC_META
#define BASS_SYNC_META 4
BASS_SYNC_MIXTIME
#define BASS_SYNC_MIXTIME 0x40000000
BASS_SYNC_MUSICFX
#define BASS_SYNC_MUSICFX 3
BASS_SYNC_MUSICINST
#define BASS_SYNC_MUSICINST 1
BASS_SYNC_MUSICPOS
#define BASS_SYNC_MUSICPOS 10
BASS_SYNC_OGG_CHANGE
#define BASS_SYNC_OGG_CHANGE 12
BASS_SYNC_ONETIME
#define BASS_SYNC_ONETIME 0x80000000
BASS_SYNC_POS
#define BASS_SYNC_POS 0
BASS_SYNC_SETPOS
#define BASS_SYNC_SETPOS 11
BASS_SYNC_SLIDE
#define BASS_SYNC_SLIDE 5
BASS_SYNC_STALL
#define BASS_SYNC_STALL 6
BASS_TAG_AM_MIME
#define BASS_TAG_AM_MIME 15
BASS_TAG_AM_NAME
#define BASS_TAG_AM_NAME 16
BASS_TAG_APE
#define BASS_TAG_APE 6
BASS_TAG_APE_BINARY
#define BASS_TAG_APE_BINARY 0x1000
BASS_TAG_CA_CODEC
#define BASS_TAG_CA_CODEC 11
BASS_TAG_HTTP
#define BASS_TAG_HTTP 3
BASS_TAG_ICY
#define BASS_TAG_ICY 4
BASS_TAG_ID3
#define BASS_TAG_ID3 0
BASS_TAG_ID3V2
#define BASS_TAG_ID3V2 1
BASS_TAG_LYRICS3
#define BASS_TAG_LYRICS3 10
BASS_TAG_META
#define BASS_TAG_META 5
BASS_TAG_MF
#define BASS_TAG_MF 13
BASS_TAG_MP4
#define BASS_TAG_MP4 7
BASS_TAG_MUSIC_AUTH
#define BASS_TAG_MUSIC_AUTH 0x10003
BASS_TAG_MUSIC_INST
#define BASS_TAG_MUSIC_INST 0x10100
BASS_TAG_MUSIC_MESSAGE
#define BASS_TAG_MUSIC_MESSAGE 0x10001
BASS_TAG_MUSIC_NAME
#define BASS_TAG_MUSIC_NAME 0x10000
BASS_TAG_MUSIC_ORDERS
#define BASS_TAG_MUSIC_ORDERS 0x10002
BASS_TAG_MUSIC_SAMPLE
#define BASS_TAG_MUSIC_SAMPLE 0x10300
BASS_TAG_OGG
#define BASS_TAG_OGG 2
BASS_TAG_RIFF_BEXT
#define BASS_TAG_RIFF_BEXT 0x101
BASS_TAG_RIFF_CART
#define BASS_TAG_RIFF_CART 0x102
BASS_TAG_RIFF_CUE
#define BASS_TAG_RIFF_CUE 0x104
BASS_TAG_RIFF_DISP
#define BASS_TAG_RIFF_DISP 0x103
BASS_TAG_RIFF_INFO
#define BASS_TAG_RIFF_INFO 0x100
BASS_TAG_RIFF_SMPL
#define BASS_TAG_RIFF_SMPL 0x105
BASS_TAG_VENDOR
#define BASS_TAG_VENDOR 9
BASS_TAG_WAVEFORMAT
#define BASS_TAG_WAVEFORMAT 14
BASS_TAG_WMA
#define BASS_TAG_WMA 8
BASS_UNICODE
#define BASS_UNICODE 0x80000000
BASS_VAM_HARDWARE
#define BASS_VAM_HARDWARE 1
BASS_VAM_SOFTWARE
#define BASS_VAM_SOFTWARE 2
BASS_VAM_TERM_DIST
#define BASS_VAM_TERM_DIST 8
BASS_VAM_TERM_PRIO
#define BASS_VAM_TERM_PRIO 16
BASS_VAM_TERM_TIME
#define BASS_VAM_TERM_TIME 4
BASSDEF
#define BASSDEF (f) WINAPI f
BASSVERSION
#define BASSVERSION 0x204
BASSVERSIONTEXT
#define BASSVERSIONTEXT "2.4"
CALLBACK
#define CALLBACK
DSCAPS_CERTIFIED
#define DSCAPS_CERTIFIED 0x00000040
DSCAPS_CONTINUOUSRATE
#define DSCAPS_CONTINUOUSRATE 0x00000010
DSCAPS_EMULDRIVER
#define DSCAPS_EMULDRIVER 0x00000020
DSCAPS_SECONDARY16BIT
#define DSCAPS_SECONDARY16BIT 0x00000800
DSCAPS_SECONDARY8BIT
#define DSCAPS_SECONDARY8BIT 0x00000400
DSCAPS_SECONDARYMONO
#define DSCAPS_SECONDARYMONO 0x00000100
DSCAPS_SECONDARYSTEREO
#define DSCAPS_SECONDARYSTEREO 0x00000200
DSCCAPS_CERTIFIED
#define DSCCAPS_CERTIFIED DSCAPS_CERTIFIED
DSCCAPS_EMULDRIVER
#define DSCCAPS_EMULDRIVER DSCAPS_EMULDRIVER
EAX_PRESET_ALLEY
#define EAX_PRESET_ALLEY EAX_ENVIRONMENT_ALLEY,0.25F,1.752F,0.776F
EAX_PRESET_ARENA
#define EAX_PRESET_ARENA EAX_ENVIRONMENT_ARENA,0.361F,7.284F,0.332F
EAX_PRESET_AUDITORIUM
#define EAX_PRESET_AUDITORIUM EAX_ENVIRONMENT_AUDITORIUM,0.403F,4.279F,0.5F
EAX_PRESET_BATHROOM
#define EAX_PRESET_BATHROOM EAX_ENVIRONMENT_BATHROOM,0.653F,1.499F,0.166F
EAX_PRESET_CARPETEDHALLWAY
#define EAX_PRESET_CARPETEDHALLWAY EAX_ENVIRONMENT_CARPETEDHALLWAY,0.153F,0.259F,2.0F
EAX_PRESET_CAVE
#define EAX_PRESET_CAVE EAX_ENVIRONMENT_CAVE,0.5F,2.886F,1.304F
EAX_PRESET_CITY
#define EAX_PRESET_CITY EAX_ENVIRONMENT_CITY,0.111F,2.767F,0.224F
EAX_PRESET_CONCERTHALL
#define EAX_PRESET_CONCERTHALL EAX_ENVIRONMENT_CONCERTHALL,0.5F,3.961F,0.5F
EAX_PRESET_DIZZY
#define EAX_PRESET_DIZZY EAX_ENVIRONMENT_DIZZY,0.139F,17.234F,0.666F
EAX_PRESET_DRUGGED
#define EAX_PRESET_DRUGGED EAX_ENVIRONMENT_DRUGGED,0.875F,8.392F,1.388F
EAX_PRESET_FOREST
#define EAX_PRESET_FOREST EAX_ENVIRONMENT_FOREST,0.111F,3.145F,0.472F
EAX_PRESET_GENERIC
#define EAX_PRESET_GENERIC EAX_ENVIRONMENT_GENERIC,0.5F,1.493F,0.5F
EAX_PRESET_HALLWAY
#define EAX_PRESET_HALLWAY EAX_ENVIRONMENT_HALLWAY,0.361F,1.493F,0.0F
EAX_PRESET_HANGAR
#define EAX_PRESET_HANGAR EAX_ENVIRONMENT_HANGAR,0.5F,10.0F,0.3F
EAX_PRESET_LIVINGROOM
#define EAX_PRESET_LIVINGROOM EAX_ENVIRONMENT_LIVINGROOM,0.208F,0.478F,0.0F
EAX_PRESET_MOUNTAINS
#define EAX_PRESET_MOUNTAINS EAX_ENVIRONMENT_MOUNTAINS,0.194F,7.841F,0.472F
EAX_PRESET_PADDEDCELL
#define EAX_PRESET_PADDEDCELL EAX_ENVIRONMENT_PADDEDCELL,0.25F,0.1F,0.0F
EAX_PRESET_PARKINGLOT
#define EAX_PRESET_PARKINGLOT EAX_ENVIRONMENT_PARKINGLOT,0.208F,1.652F,1.5F
EAX_PRESET_PLAIN
#define EAX_PRESET_PLAIN EAX_ENVIRONMENT_PLAIN,0.097F,2.767F,0.224F
EAX_PRESET_PSYCHOTIC
#define EAX_PRESET_PSYCHOTIC EAX_ENVIRONMENT_PSYCHOTIC,0.486F,7.563F,0.806F
EAX_PRESET_QUARRY
#define EAX_PRESET_QUARRY EAX_ENVIRONMENT_QUARRY,1.0F,1.499F,0.5F
EAX_PRESET_ROOM
#define EAX_PRESET_ROOM EAX_ENVIRONMENT_ROOM,0.417F,0.4F,0.666F
EAX_PRESET_SEWERPIPE
#define EAX_PRESET_SEWERPIPE EAX_ENVIRONMENT_SEWERPIPE,0.652F,2.886F,0.25F
EAX_PRESET_STONECORRIDOR
#define EAX_PRESET_STONECORRIDOR EAX_ENVIRONMENT_STONECORRIDOR,0.444F,2.697F,0.638F
EAX_PRESET_STONEROOM
#define EAX_PRESET_STONEROOM EAX_ENVIRONMENT_STONEROOM,0.5F,2.309F,0.888F
EAX_PRESET_UNDERWATER
#define EAX_PRESET_UNDERWATER EAX_ENVIRONMENT_UNDERWATER,1.0F,1.499F,0.0F
FALSE
#define FALSE 0
HIBYTE
#define HIBYTE (a) (BYTE)((a)>>8)
HIWORD
#define HIWORD (a) (WORD)((a)>>16)
LOBYTE
#define LOBYTE (a) (BYTE)(a)
LOWORD
#define LOWORD (a) (WORD)(a)
MAKELONG
#define MAKELONG (a, b) (DWORD)(((a)&0xffff)|((b)<<16))
MAKEWORD
#define MAKEWORD (a, b) (WORD)(((a)&0xff)|((b)<<8))
STREAMFILE_BUFFER
#define STREAMFILE_BUFFER 1
STREAMFILE_BUFFERPUSH
#define STREAMFILE_BUFFERPUSH 2
STREAMFILE_NOBUFFER
#define STREAMFILE_NOBUFFER 0
STREAMPROC_DEVICE
#define STREAMPROC_DEVICE (STREAMPROC*)-2
STREAMPROC_DUMMY
#define STREAMPROC_DUMMY (STREAMPROC*)0
STREAMPROC_PUSH
#define STREAMPROC_PUSH (STREAMPROC*)-1
TRUE
#define TRUE 1
WAVE_FORMAT_1M08
#define WAVE_FORMAT_1M08 0x00000001 /* 11.025 kHz, Mono, 8-bit */
WAVE_FORMAT_1M16
#define WAVE_FORMAT_1M16 0x00000004 /* 11.025 kHz, Mono, 16-bit */
WAVE_FORMAT_1S08
#define WAVE_FORMAT_1S08 0x00000002 /* 11.025 kHz, Stereo, 8-bit */
WAVE_FORMAT_1S16
#define WAVE_FORMAT_1S16 0x00000008 /* 11.025 kHz, Stereo, 16-bit */
WAVE_FORMAT_2M08
#define WAVE_FORMAT_2M08 0x00000010 /* 22.05 kHz, Mono, 8-bit */
WAVE_FORMAT_2M16
#define WAVE_FORMAT_2M16 0x00000040 /* 22.05 kHz, Mono, 16-bit */
WAVE_FORMAT_2S08
#define WAVE_FORMAT_2S08 0x00000020 /* 22.05 kHz, Stereo, 8-bit */
WAVE_FORMAT_2S16
#define WAVE_FORMAT_2S16 0x00000080 /* 22.05 kHz, Stereo, 16-bit */
WAVE_FORMAT_4M08
#define WAVE_FORMAT_4M08 0x00000100 /* 44.1 kHz, Mono, 8-bit */
WAVE_FORMAT_4M16
#define WAVE_FORMAT_4M16 0x00000400 /* 44.1 kHz, Mono, 16-bit */
WAVE_FORMAT_4S08
#define WAVE_FORMAT_4S08 0x00000200 /* 44.1 kHz, Stereo, 8-bit */
WAVE_FORMAT_4S16
#define WAVE_FORMAT_4S16 0x00000800 /* 44.1 kHz, Stereo, 16-bit */
WINAPI
#define WINAPI
Typedef Documentation
BASS_3DVECTOR
typedef struct BASS_3DVECTOR BASS_3DVECTOR
BOOL
typedef BOOL
buffer
typedef const void * buffer
BYTE
typedef uint8_t BYTE
channel
typedef DWORD channel
data
typedef DWORD DWORD data
DWORD
typedef DWORD
HCHANNEL
typedef DWORD HCHANNEL
HDSP
typedef DWORD HDSP
HFX
typedef DWORD HFX
HMUSIC
typedef DWORD HMUSIC
HPLUGIN
typedef DWORD HPLUGIN
HRECORD
typedef DWORD HRECORD
HSAMPLE
typedef DWORD HSAMPLE
HSTREAM
typedef DWORD HSTREAM
HSYNC
typedef DWORD HSYNC
length
typedef const void DWORD length
LPCWAVEFORMATEX
typedef const WAVEFORMATEX* LPCWAVEFORMATEX
LPWAVEFORMATEX
typedef struct tWAVEFORMATEX * LPWAVEFORMATEX
PWAVEFORMATEX
typedef struct tWAVEFORMATEX * PWAVEFORMATEX
QWORD
typedef uint64_t QWORD
user
typedef const void DWORD void * user
WAVEFORMATEX
typedef struct tWAVEFORMATEX WAVEFORMATEX
WORD
typedef uint16_t WORD
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EAX_ENVIRONMENT_GENERIC
EAX_ENVIRONMENT_PADDEDCELL
EAX_ENVIRONMENT_ROOM
EAX_ENVIRONMENT_BATHROOM
EAX_ENVIRONMENT_LIVINGROOM
EAX_ENVIRONMENT_STONEROOM
EAX_ENVIRONMENT_AUDITORIUM
EAX_ENVIRONMENT_CONCERTHALL
EAX_ENVIRONMENT_CAVE
EAX_ENVIRONMENT_ARENA
EAX_ENVIRONMENT_HANGAR
EAX_ENVIRONMENT_CARPETEDHALLWAY
EAX_ENVIRONMENT_HALLWAY
EAX_ENVIRONMENT_STONECORRIDOR
EAX_ENVIRONMENT_ALLEY
EAX_ENVIRONMENT_FOREST
EAX_ENVIRONMENT_CITY
EAX_ENVIRONMENT_MOUNTAINS
EAX_ENVIRONMENT_QUARRY
EAX_ENVIRONMENT_PLAIN
EAX_ENVIRONMENT_PARKINGLOT
EAX_ENVIRONMENT_SEWERPIPE
EAX_ENVIRONMENT_UNDERWATER
EAX_ENVIRONMENT_DRUGGED
EAX_ENVIRONMENT_DIZZY
EAX_ENVIRONMENT_PSYCHOTIC
EAX_ENVIRONMENT_COUNT
Function Documentation
BASS_Apply3D()
void BASSDEF() BASS_Apply3D ()
BASS_ChannelBytes2Seconds()
double BASSDEF() BASS_ChannelBytes2Seconds (DWORD handle, QWORD pos)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelFlags()
DWORD BASSDEF() BASS_ChannelFlags (DWORD handle, DWORD flags, DWORD mask)
BASS_ChannelGet3DAttributes()
BOOL BASSDEF() BASS_ChannelGet3DAttributes (DWORD handle, DWORD * mode, float * min, float * max, DWORD * iangle, DWORD * oangle, float * outvol)
BASS_ChannelGet3DPosition()
BOOL BASSDEF() BASS_ChannelGet3DPosition (DWORD handle, BASS_3DVECTOR * pos, BASS_3DVECTOR * orient, BASS_3DVECTOR * vel)
BASS_ChannelGetAttribute()
BOOL BASSDEF() BASS_ChannelGetAttribute (DWORD handle, DWORD attrib, float * value)
BASS_ChannelGetAttributeEx()
DWORD BASSDEF() BASS_ChannelGetAttributeEx (DWORD handle, DWORD attrib, void * value, DWORD size)
BASS_ChannelGetData()
DWORD BASSDEF() BASS_ChannelGetData (DWORD handle, void * buffer, DWORD length)
BASS_ChannelGetDevice()
DWORD BASSDEF() BASS_ChannelGetDevice (DWORD handle)
BASS_ChannelGetInfo()
BOOL BASSDEF() BASS_ChannelGetInfo (DWORD handle, BASS_CHANNELINFO * info)
BASS_ChannelGetLength()
QWORD BASSDEF() BASS_ChannelGetLength (DWORD handle, DWORD mode)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelGetLevel()
DWORD BASSDEF() BASS_ChannelGetLevel (DWORD handle)
BASS_ChannelGetLevelEx()
BOOL BASSDEF() BASS_ChannelGetLevelEx (DWORD handle, float * levels, float length, DWORD flags)
BASS_ChannelGetPosition()
QWORD BASSDEF() BASS_ChannelGetPosition (DWORD handle, DWORD mode)
BASS_ChannelGetTags()
const char* BASSDEF() BASS_ChannelGetTags (DWORD handle, DWORD tags)
BASS_ChannelIsActive()
DWORD BASSDEF() BASS_ChannelIsActive (DWORD handle)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelIsSliding()
BOOL BASSDEF() BASS_ChannelIsSliding (DWORD handle, DWORD attrib)
BASS_ChannelLock()
BOOL BASSDEF() BASS_ChannelLock (DWORD handle, BOOL lock)
BASS_ChannelPause()
BOOL BASSDEF() BASS_ChannelPause (DWORD handle)
BASS_ChannelPlay()
BOOL BASSDEF() BASS_ChannelPlay (DWORD handle, BOOL restart)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelRemoveDSP()
BOOL BASSDEF() BASS_ChannelRemoveDSP (DWORD handle, HDSP dsp)
BASS_ChannelRemoveFX()
BOOL BASSDEF() BASS_ChannelRemoveFX (DWORD handle, HFX fx)
BASS_ChannelRemoveLink()
BOOL BASSDEF() BASS_ChannelRemoveLink (DWORD handle, DWORD chan)
BASS_ChannelRemoveSync()
BOOL BASSDEF() BASS_ChannelRemoveSync (DWORD handle, HSYNC sync)
BASS_ChannelSeconds2Bytes()
QWORD BASSDEF() BASS_ChannelSeconds2Bytes (DWORD handle, double pos)
BASS_ChannelSet3DAttributes()
BOOL BASSDEF() BASS_ChannelSet3DAttributes (DWORD handle, int mode, float min, float max, int iangle, int oangle, float outvol)
BASS_ChannelSet3DPosition()
BOOL BASSDEF() BASS_ChannelSet3DPosition (DWORD handle, const BASS_3DVECTOR * pos, const BASS_3DVECTOR * orient, const BASS_3DVECTOR * vel)
BASS_ChannelSetAttribute()
BOOL BASSDEF() BASS_ChannelSetAttribute (DWORD handle, DWORD attrib, float value)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelSetAttributeEx()
BOOL BASSDEF() BASS_ChannelSetAttributeEx (DWORD handle, DWORD attrib, void * value, DWORD size)
BASS_ChannelSetDevice()
BOOL BASSDEF() BASS_ChannelSetDevice (DWORD handle, DWORD device)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelSetDSP()
HDSP BASSDEF() BASS_ChannelSetDSP (DWORD handle, DSPPROC * proc, void * user, int priority)
BASS_ChannelSetFX()
HFX BASSDEF() BASS_ChannelSetFX (DWORD handle, DWORD type, int priority)
Referenced by CustomPlayer::PlayAt().
BASS_ChannelSetLink()
BOOL BASSDEF() BASS_ChannelSetLink (DWORD handle, DWORD chan)
BASS_ChannelSetPosition()
BOOL BASSDEF() BASS_ChannelSetPosition (DWORD handle, QWORD pos, DWORD mode)
BASS_ChannelSetSync()
HSYNC BASSDEF() BASS_ChannelSetSync (DWORD handle, DWORD type, QWORD param, SYNCPROC * proc, void * user)
BASS_ChannelSlideAttribute()
BOOL BASSDEF() BASS_ChannelSlideAttribute (DWORD handle, DWORD attrib, float value, DWORD time)
BASS_ChannelStop()
BOOL BASSDEF() BASS_ChannelStop (DWORD handle)
Referenced by CustomPlayer::Stop().
BASS_ChannelUpdate()
BOOL BASSDEF() BASS_ChannelUpdate (DWORD handle, DWORD length)
BASS_ErrorGetCode()
int BASSDEF() BASS_ErrorGetCode ()
BASS_Free()
BOOL BASSDEF() BASS_Free ()
BASS_FXGetParameters()
BOOL BASSDEF() BASS_FXGetParameters (HFX handle, void * params)
BASS_FXReset()
BOOL BASSDEF() BASS_FXReset (HFX handle)
BASS_FXSetParameters()
BOOL BASSDEF() BASS_FXSetParameters (HFX handle, const void * params)
Referenced by CustomPlayer::PlayAt().
BASS_FXSetPriority()
BOOL BASSDEF() BASS_FXSetPriority (HFX handle, int priority)
BASS_Get3DFactors()
BOOL BASSDEF() BASS_Get3DFactors (float * distf, float * rollf, float * doppf)
BASS_Get3DPosition()
BOOL BASSDEF() BASS_Get3DPosition (BASS_3DVECTOR * pos, BASS_3DVECTOR * vel, BASS_3DVECTOR * front, BASS_3DVECTOR * top)
BASS_GetConfig()
DWORD BASSDEF() BASS_GetConfig (DWORD option)
BASS_GetConfigPtr()
void* BASSDEF() BASS_GetConfigPtr (DWORD option)
BASS_GetCPU()
float BASSDEF() BASS_GetCPU ()
BASS_GetDevice()
DWORD BASSDEF() BASS_GetDevice ()
BASS_GetDeviceInfo()
BOOL BASSDEF() BASS_GetDeviceInfo (DWORD device, BASS_DEVICEINFO * info)
Referenced by SoundboardMainUI::fetchDeviceList().
BASS_GetInfo()
BOOL BASSDEF() BASS_GetInfo (BASS_INFO * info)
BASS_GetVersion()
DWORD BASSDEF() BASS_GetVersion ()
BASS_GetVolume()
float BASSDEF() BASS_GetVolume ()
BASS_Init()
BOOL BASSDEF() BASS_Init (int device, DWORD freq, DWORD flags, void * win, void * dsguid)
Referenced by CustomPlayer::PlayAt().
BASS_MusicFree()
BOOL BASSDEF() BASS_MusicFree (HMUSIC handle)
BASS_MusicLoad()
HMUSIC BASSDEF() BASS_MusicLoad (BOOL mem, const void * file, QWORD offset, DWORD length, DWORD flags, DWORD freq)
BASS_Pause()
BOOL BASSDEF() BASS_Pause ()
BASS_PluginFree()
BOOL BASSDEF() BASS_PluginFree (HPLUGIN handle)
BASS_PluginGetInfo()
const BASS_PLUGININFO* BASSDEF() BASS_PluginGetInfo (HPLUGIN handle)
BASS_PluginLoad()
HPLUGIN BASSDEF() BASS_PluginLoad (const char * file, DWORD flags)
BASS_RecordFree()
BOOL BASSDEF() BASS_RecordFree ()
BASS_RecordGetDevice()
DWORD BASSDEF() BASS_RecordGetDevice ()
BASS_RecordGetDeviceInfo()
BOOL BASSDEF() BASS_RecordGetDeviceInfo (DWORD device, BASS_DEVICEINFO * info)
Referenced by SoundboardMainUI::fetchDeviceList().
BASS_RecordGetInfo()
BOOL BASSDEF() BASS_RecordGetInfo (BASS_RECORDINFO * info)
BASS_RecordGetInput()
DWORD BASSDEF() BASS_RecordGetInput (int input, float * volume)
BASS_RecordGetInputName()
const char* BASSDEF() BASS_RecordGetInputName (int input)
BASS_RecordInit()
BOOL BASSDEF() BASS_RecordInit (int device)
BASS_RecordSetDevice()
BOOL BASSDEF() BASS_RecordSetDevice (DWORD device)
BASS_RecordSetInput()
BOOL BASSDEF() BASS_RecordSetInput (int input, DWORD flags, float volume)
BASS_RecordStart()
HRECORD BASSDEF() BASS_RecordStart (DWORD freq, DWORD chans, DWORD flags, RECORDPROC * proc, void * user)
BASS_SampleCreate()
HSAMPLE BASSDEF() BASS_SampleCreate (DWORD length, DWORD freq, DWORD chans, DWORD max, DWORD flags)
BASS_SampleFree()
BOOL BASSDEF() BASS_SampleFree (HSAMPLE handle)
BASS_SampleGetChannel()
HCHANNEL BASSDEF() BASS_SampleGetChannel (HSAMPLE handle, BOOL onlynew)
BASS_SampleGetChannels()
DWORD BASSDEF() BASS_SampleGetChannels (HSAMPLE handle, HCHANNEL * channels)
BASS_SampleGetData()
BOOL BASSDEF() BASS_SampleGetData (HSAMPLE handle, void * buffer)
BASS_SampleGetInfo()
BOOL BASSDEF() BASS_SampleGetInfo (HSAMPLE handle, BASS_SAMPLE * info)
BASS_SampleLoad()
HSAMPLE BASSDEF() BASS_SampleLoad (BOOL mem, const void * file, QWORD offset, DWORD length, DWORD max, DWORD flags)
BASS_SampleSetData()
BOOL BASSDEF() BASS_SampleSetData (HSAMPLE handle, const void * buffer)
BASS_SampleSetInfo()
BOOL BASSDEF() BASS_SampleSetInfo (HSAMPLE handle, const BASS_SAMPLE * info)
BASS_SampleStop()
BOOL BASSDEF() BASS_SampleStop (HSAMPLE handle)
BASS_Set3DFactors()
BOOL BASSDEF() BASS_Set3DFactors (float distf, float rollf, float doppf)
BASS_Set3DPosition()
BOOL BASSDEF() BASS_Set3DPosition (const BASS_3DVECTOR * pos, const BASS_3DVECTOR * vel, const BASS_3DVECTOR * front, const BASS_3DVECTOR * top)
BASS_SetConfig()
BOOL BASSDEF() BASS_SetConfig (DWORD option, DWORD value)
BASS_SetConfigPtr()
BOOL BASSDEF() BASS_SetConfigPtr (DWORD option, const void * value)
BASS_SetDevice()
BOOL BASSDEF() BASS_SetDevice (DWORD device)
BASS_SetVolume()
BOOL BASSDEF() BASS_SetVolume (float volume)
BASS_Start()
BOOL BASSDEF() BASS_Start ()
BASS_Stop()
BOOL BASSDEF() BASS_Stop ()
BASS_StreamCreate()
HSTREAM BASSDEF() BASS_StreamCreate (DWORD freq, DWORD chans, DWORD flags, STREAMPROC * proc, void * user)
BASS_StreamCreateFile()
HSTREAM BASSDEF() BASS_StreamCreateFile (BOOL mem, const void * file, QWORD offset, QWORD length, DWORD flags)
Referenced by CustomPlayer::PlayAt().
BASS_StreamCreateFileUser()
HSTREAM BASSDEF() BASS_StreamCreateFileUser (DWORD system, DWORD flags, const BASS_FILEPROCS * proc, void * user)
BASS_StreamCreateURL()
HSTREAM BASSDEF() BASS_StreamCreateURL (const char * url, DWORD offset, DWORD flags, DOWNLOADPROC * proc, void * user)
Referenced by CustomPlayer::PlayAt().
BASS_StreamFree()
BOOL BASSDEF() BASS_StreamFree (HSTREAM handle)
BASS_StreamGetFilePosition()
QWORD BASSDEF() BASS_StreamGetFilePosition (HSTREAM handle, DWORD mode)
BASS_StreamPutData()
DWORD BASSDEF() BASS_StreamPutData (HSTREAM handle, const void * buffer, DWORD length)
BASS_StreamPutFileData()
DWORD BASSDEF() BASS_StreamPutFileData (HSTREAM handle, const void * buffer, DWORD length)
BASS_Update()
BOOL BASSDEF() BASS_Update (DWORD length)
BOOL()
typedef BOOL (CALLBACK FILESEEKPROC)
DWORD()
typedef DWORD (CALLBACK STREAMPROC)
QWORD()
typedef QWORD (CALLBACK FILELENPROC)
void()
typedef void (CALLBACK FILECLOSEPROC)
Referenced by GameSelector::GameSelector(), and LIDL::Controller::SettingsController::ShowSettingsWindow().