LIDL Soundboard: Profile::Builder Class Reference
Profile::Builder Class Reference
#include <Profile.h>
Public Member Functions
Builder ()
Builder & setName (QString name)
Builder & addExe (QString exe)
Builder & setParent (Profile *parent)
Builder & setSounds (QVector< std::shared_ptr< SoundWrapper >> wrappers)
Builder & setPttVirtualKey (int vk)
Builder & setPttScanCode (int sc)
Builder & setPttKeySequence (QKeySequence ks)
Profile * Build ()
Private Attributes
QSet< QString > _exeList
QString _name = "Default"
Profile * _parent = nullptr
QVector< std::shared_ptr< SoundWrapper > > _wrappers
int _pttVirtualKey = -1
int _pttScanCode = -1
QKeySequence _pttKeySequence = QKeySequence()
Constructor & Destructor Documentation
Builder()
Profile::Builder::Builder () inline
References _wrappers.
Member Function Documentation
addExe()
Builder& Profile::Builder::addExe (QString exe) inline
Referenced by LIDL::Controller::SaveController::OpenSaveFile().
Build()
Profile* Profile::Builder::Build () inline
References _exeList, _name, _parent, _pttKeySequence, _pttScanCode, _pttVirtualKey, _wrappers, and Profile::Profile().
Referenced by LIDL::Controller::SaveController::OpenSaveFile(), and LIDL::Controller::SaveController::ParseOldSave().
setName()
Builder& Profile::Builder::setName (QString name) inline
Referenced by LIDL::Controller::SaveController::OpenSaveFile().
setParent()
Builder& Profile::Builder::setParent (Profile * parent) inline
setPttKeySequence()
Builder& Profile::Builder::setPttKeySequence (QKeySequence ks) inline
Referenced by LIDL::Controller::SaveController::OpenSaveFile(), and LIDL::Controller::SaveController::ParseOldSave().
setPttScanCode()
Builder& Profile::Builder::setPttScanCode (int sc) inline
Referenced by LIDL::Controller::SaveController::OpenSaveFile(), and LIDL::Controller::SaveController::ParseOldSave().
setPttVirtualKey()
Builder& Profile::Builder::setPttVirtualKey (int vk) inline
Referenced by LIDL::Controller::SaveController::OpenSaveFile(), and LIDL::Controller::SaveController::ParseOldSave().
setSounds()
Builder& Profile::Builder::setSounds (QVector< std::shared_ptr< SoundWrapper >> wrappers) inline
Referenced by LIDL::Controller::SaveController::OpenSaveFile(), and LIDL::Controller::SaveController::ParseOldSave().
Member Data Documentation
_exeList
QSet<QString> Profile::Builder::_exeList private
Array of executables
Referenced by Build().
_name
QString Profile::Builder::_name = "Default" private
Referenced by Build().
_parent
Profile* Profile::Builder::_parent = nullptr private
Referenced by Build().
_pttKeySequence
QKeySequence Profile::Builder::_pttKeySequence = QKeySequence() private
Referenced by Build().
_pttScanCode
int Profile::Builder::_pttScanCode = -1 private
Referenced by Build().
_pttVirtualKey
int Profile::Builder::_pttVirtualKey = -1 private
Referenced by Build().
_wrappers
QVector<std::shared_ptr<SoundWrapper> > Profile::Builder::_wrappers private
Referenced by Build(), and Builder().
The documentation for this class was generated from the following file:
D:/Qt/Projects/Lidl_Soundboard/include/Profile.h