LIDL Soundboard: MouseButtonSignaler Class Reference
MouseButtonSignaler Class Reference
#include <framelesswindow.h>
Signals
void mouseButtonEvent (QWidget *, QMouseEvent *)
Public Member Functions
MouseButtonSignaler (QObject *parent=0)
void installOn (QWidget *widget)
Protected Member Functions
virtual bool eventFilter (QObject *obj, QEvent *ev) Q_DECL_OVERRIDE
Constructor & Destructor Documentation
MouseButtonSignaler()
MouseButtonSignaler::MouseButtonSignaler (QObject * parent = 0) inline
Member Function Documentation
eventFilter()
virtual bool MouseButtonSignaler::eventFilter (QObject * obj, QEvent * ev) inline protected virtual
References mouseButtonEvent().
installOn()
void MouseButtonSignaler::installOn (QWidget * widget) inline
Referenced by FramelessWindow::FramelessWindow().
mouseButtonEvent
void MouseButtonSignaler::mouseButtonEvent (QWidget * , QMouseEvent *) signal
Referenced by eventFilter(), and FramelessWindow::FramelessWindow().
The documentation for this class was generated from the following file:
D:/Qt/Projects/Lidl_Soundboard/include/framelesswindow.h