LIDL Soundboard: LIDL::Controller::HookController Class Reference
LIDL::Controller::HookController Class Reference
The HookController class.
#include <HookController.h>
Public Member Functions
void SetHooks ()
SetHooks Sets up the hooks.
void UnSetHooks ()
UnSetHooks Unregister the hooks (before closing app, because if you don't unregister them close the app, and switch to another window fast it will trigger a "must construct QApplication before QPixMap" error and crash because of the overlay still trying to show.
Static Public Member Functions
static HookController * GetInstance ()
GetInstace.
static Profile * GetProfileForExe (HWND handle)
GetProfileForExe.
Private Member Functions
HookController ()
Private Attributes
QVector< HWINEVENTHOOK > _hookHandles
Static Private Attributes
static HookController * self = nullptr
Detailed Description
The HookController class.
The singleton dealing with registering and unregistering the WinApi hooks
Constructor & Destructor Documentation
HookController()
LIDL::Controller::HookController::HookController () private
Referenced by GetInstance().
Member Function Documentation
GetInstance()
HookController * LIDL::Controller::HookController::GetInstance () static
GetInstace.
Returns
References HookController().
Referenced by SoundboardMainUI::closeEvent(), and SoundboardMainUI::SoundboardMainUI().
GetProfileForExe()
Profile * LIDL::Controller::HookController::GetProfileForExe (HWND handle) static
GetProfileForExe.
Returns
A pointer to the correct profile, or nullptr if no profile was found !
Basically will: Get the full path to the executable linked to the window Transform it to linux style path with forward slash Search for it in the array of profile using the designated method in SettingsController
References FALSE, LIDL::Controller::ProfileController::GetInstance(), and LIDL::Controller::ProfileController::GetProfileForExe().
Referenced by LIDL::Callback::ShowOverlay().
SetHooks()
void LIDL::Controller::HookController::SetHooks ()
SetHooks Sets up the hooks.
References _hookHandles, LIDL::Callback::ResizeToWindow(), LIDL::Callback::ShowOverlay(), and UnSetHooks().
Referenced by SoundboardMainUI::SoundboardMainUI().
UnSetHooks()
void LIDL::Controller::HookController::UnSetHooks ()
UnSetHooks Unregister the hooks (before closing app, because if you don't unregister them close the app, and switch to another window fast it will trigger a "must construct QApplication before QPixMap" error and crash because of the overlay still trying to show.
References _hookHandles.
Referenced by SoundboardMainUI::closeEvent(), and SetHooks().
Member Data Documentation
_hookHandles
QVector<HWINEVENTHOOK> LIDL::Controller::HookController::_hookHandles private
Referenced by SetHooks(), and UnSetHooks().
self
HookController * LIDL::Controller::HookController::self = nullptr static private
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/HookController.h
D:/Qt/Projects/Lidl_Soundboard/source/HookController.cpp