LIDL Soundboard: SfxSettingsWidget Class Reference
SfxSettingsWidget Class Reference
#include <SfxSettingsWidget.h>
Signals
void sliderValueChanged (int sliderIndex, int newValue, int specialValue)
sliderValueChanged Emitted when a slider's value changed.
void comboBoxValueChanged (int comboBoxIndex, int newIndex, int enumValue)
comboBoxValueChanged Emitted when a combo box text has changed.
void checkBoxStateChanged (bool newState)
checkBoxStateChanged Emitted when checkbox is toggled.
Public Member Functions
SfxSettingsWidget (QWidget *parent=nullptr)
SfxSettingsWidget Default constructor.
SfxSettingsWidget (QString sfxName, LIDL::SFX_TYPE type=LIDL::SFX_TYPE::NONE, bool showCheckmarkAndPresets=true, QWidget *parent=nullptr)
SfxSettingsWidget Overloaded constructor to account for SFX name.
void addSlider (QString label="", int min=0, int max=100, QString suffix="", int specialValue=-1, QString prefix="")
addSlider
void addComboBox (QString label, QStringList values, int enumValue=-1)
addComboBox Add a combo box to the widget.
void setSliderValue (int sliderIndex, int newValue)
setSliderValue Set a slider's value.
void setComboBoxIndex (int comboIndex, int newItemIndex)
setComboBoxIndex Set a combobox's displayed item.
void setValueOfEnumParam (int enumValue, int newValue)
setValueOfEnumParam Will set the value of a widget item settings.
int getValueOfEnumParam (int enumValue) const
getValueOfEnumParam Get the value of a widget item settings.
void setCheckboxState (bool state)
setCheckboxState Set this widget checkbox checked state.
void deactivateAll ()
deactivateAll Deactivates all widgets except the checkbox.
void addSpacer ()
addSpacer Add a spacer to the layout so that every one have the same line height.
QSize sizeHint () const
sizeHint Reimplemented to account for the QScrollArea so that the spoiler doesn't make a mess.
std::map< int, int > getSFXAsMap () const
getSFXAsStructure Returns the SFX structure associated with the widget
Private Attributes
QWidget * _container
QCheckBox * _checkbox
QGridLayout * _layout
QVector< SliderSpin * > _sliders
QVector< QComboBox * > _comboBox
std::map< int, QWidget * > _specialMap
QComboBox * _presetBox
LIDL::SFX_TYPE _type
Constructor & Destructor Documentation
SfxSettingsWidget() [1/2]
SfxSettingsWidget::SfxSettingsWidget (QWidget * parent = nullptr) explicit
SfxSettingsWidget Default constructor.
Sets widget and QScrollArea properties to achieve A E S T H E T I C purposes.
Parameters
parent
References _container, and _layout.
SfxSettingsWidget() [2/2]
SfxSettingsWidget::SfxSettingsWidget (QString sfxName, LIDL::SFX_TYPE type = LIDL::SFX_TYPE::NONE, bool showCheckmarkAndPresets = true, QWidget * parent = nullptr)
SfxSettingsWidget Overloaded constructor to account for SFX name.
Parameters
sfxName The sfx name. Will add a label and a checkbox for enabling/disabling purposes. \pztzm type LIDL Sfx type, used for the presets.
parent eShrug.
References _checkbox, _comboBox, _layout, _presetBox, _sliders, _type, checkBoxStateChanged(), LIDL::PresetController::GetInstance(), and LIDL::NONE.
Member Function Documentation
addComboBox()
void SfxSettingsWidget::addComboBox (QString label, QStringList values, int enumValue = -1)
addComboBox Add a combo box to the widget.
Parameters
label The label shown along the combobox.
values String List of possible values.
References _comboBox, _layout, _specialMap, and comboBoxValueChanged().
Referenced by PresetWizardIntroPage::addWidgets(), and WrapperProperties::WrapperProperties().
addSlider()
void SfxSettingsWidget::addSlider (QString label = "", int min = 0, int max = 100, QString suffix = "", int specialValue = -1, QString prefix = "")
addSlider
Parameters
label The label to be shown alongside the slider+spinbox.
min The minimum value.
max The maximum value.
suffix The suffix of the spinbox.
prefix The prefix of the spinbox.
References _layout, _sliders, _specialMap, sliderValueChanged(), and SliderSpin::valueChanged().
Referenced by PresetWizardIntroPage::addWidgets(), and WrapperProperties::WrapperProperties().
addSpacer()
void SfxSettingsWidget::addSpacer ()
addSpacer Add a spacer to the layout so that every one have the same line height.
References _layout.
Referenced by PresetWizardIntroPage::addWidgets().
checkBoxStateChanged
void SfxSettingsWidget::checkBoxStateChanged (bool newState) signal
checkBoxStateChanged Emitted when checkbox is toggled.
Parameters
newState The new state of the checkbox.
Referenced by WrapperProperties::setUpConnection(), and SfxSettingsWidget().
comboBoxValueChanged
void SfxSettingsWidget::comboBoxValueChanged (int comboBoxIndex, int newIndex, int enumValue) signal
comboBoxValueChanged Emitted when a combo box text has changed.
Parameters
comboBoxIndex The index of the combobox in the _comboBox array.
newIndex The new index of the displayed text.
enumValue The index of the settings in the enumeration (EnumsAndStruct.h).
Referenced by addComboBox(), and WrapperProperties::setUpConnection().
deactivateAll()
void SfxSettingsWidget::deactivateAll ()
deactivateAll Deactivates all widgets except the checkbox.
References _comboBox, _presetBox, and _sliders.
Referenced by WrapperProperties::setUpConnection().
getSFXAsMap()
std::map< int, int > SfxSettingsWidget::getSFXAsMap () const
getSFXAsStructure Returns the SFX structure associated with the widget
getSFXAsMap.
Returns
The sfx enumeration along side the value of the parameter.
References _specialMap.
Referenced by PresetWizardIntroPage::finished().
getValueOfEnumParam()
int SfxSettingsWidget::getValueOfEnumParam (int enumValue) const
getValueOfEnumParam Get the value of a widget item settings.
Parameters
enumValue The int representing the enum value (EnumsAndStructs.h)
Returns
References _specialMap.
setCheckboxState()
void SfxSettingsWidget::setCheckboxState (bool state)
setCheckboxState Set this widget checkbox checked state.
Parameters
state The new state of the check box (checked is true, unchecked is false).
References _checkbox.
Referenced by WrapperProperties::setUpConnection().
setComboBoxIndex()
void SfxSettingsWidget::setComboBoxIndex (int comboIndex, int newItemIndex)
setComboBoxIndex Set a combobox's displayed item.
Parameters
comboIndex Which combobox to update.
newItemIndex The index of the new item to be displayed.
References _comboBox.
setSliderValue()
void SfxSettingsWidget::setSliderValue (int sliderIndex, int newValue)
setSliderValue Set a slider's value.
Parameters
sliderIndex Which slider to update.
newValue The slider new value.
References _sliders.
setValueOfEnumParam()
void SfxSettingsWidget::setValueOfEnumParam (int enumValue, int newValue)
setValueOfEnumParam Will set the value of a widget item settings.
Will look through the std::map associating the int corresponding to the enum parameter, and a pointer to the widget that deals with it.
Parameters
enumValue The int representing the enum value (EnumsAndStructs.h).
newValue The new value.
References _specialMap.
Referenced by PresetWizardIntroPage::presetBoxIndexChanged(), and WrapperProperties::setUpConnection().
sizeHint()
QSize SfxSettingsWidget::sizeHint () const
sizeHint Reimplemented to account for the QScrollArea so that the spoiler doesn't make a mess.
Returns
The size hint.
sliderValueChanged
void SfxSettingsWidget::sliderValueChanged (int sliderIndex, int newValue, int specialValue) signal
sliderValueChanged Emitted when a slider's value changed.
Parameters
sliderIndex The index of the slider in the _sliders array.
newValue The new value.
specialValue The index of the settings in the enumeration (EnumsAndStruct.h).
Referenced by addSlider(), and WrapperProperties::setUpConnection().
Member Data Documentation
_checkbox
QCheckBox* SfxSettingsWidget::_checkbox private
Enable/disable Checkbox
Referenced by setCheckboxState(), and SfxSettingsWidget().
_comboBox
QVector<QComboBox *> SfxSettingsWidget::_comboBox private
Array of comboBox
Referenced by addComboBox(), deactivateAll(), setComboBoxIndex(), and SfxSettingsWidget().
_container
QWidget* SfxSettingsWidget::_container private
The container widget.
Referenced by SfxSettingsWidget().
_layout
QGridLayout* SfxSettingsWidget::_layout private
The layout.
Referenced by addComboBox(), addSlider(), addSpacer(), and SfxSettingsWidget().
_presetBox
QComboBox* SfxSettingsWidget::_presetBox private
Combox box displaying the differents presets available
Referenced by deactivateAll(), and SfxSettingsWidget().
_sliders
QVector<SliderSpin *> SfxSettingsWidget::_sliders private
Array of Sliders + Spinboxes
Referenced by addSlider(), deactivateAll(), setSliderValue(), and SfxSettingsWidget().
_specialMap
std::map<int, QWidget* > SfxSettingsWidget::_specialMap private
Map linking which widgets deals with witch settings (enum)
Referenced by addComboBox(), addSlider(), getSFXAsMap(), getValueOfEnumParam(), and setValueOfEnumParam().
_type
LIDL::SFX_TYPE SfxSettingsWidget::_type private
The lidl sfx type this widget is displaying.
Referenced by SfxSettingsWidget().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/SfxSettingsWidget.h
D:/Qt/Projects/Lidl_Soundboard/SfxSettingsWidget.cpp