LIDL Soundboard: SoundboardMainUI Class Reference
SoundboardMainUI Class Reference
Inherits QMainWindow.
#include <soundboardMainUI.h>
Public Slots
void addSound (std::shared_ptr< SoundWrapper > modifiedSound, int whereToInsert=-1, bool generateShortcuts=true, bool refreshView=true)
This function add a soundwrapper to the main UI display, and adds/modify the entries in the private members so that the said wrapper can be played.
void editSoundDialog ()
This function opens the Sound Entry Editor to open the selected sound. It is used by both the EDIT button and the DoubleClicked signal in the view.
void winHotKeyPressed (int handle)
Function to deal with Shortcut being pressed.
void GenerateGlobalShortcuts ()
Function to register all the Shortcuts being used by the LIDL Soundboard.
void setStopShortcut (unsigned int)
Function to register the Stop ALL Shortcut. It is used by the associated CustomShortcutEdit and the Open soundboard function.
QJsonObject * GenerateSaveFile ()
Function to generate the .lidljson save file.
void Save ()
Function save the active lidljson file. If no file is already set, it will open the Save As prompt.
void SaveAs ()
This function Opens a Save As prompt, and save the active soundboard as a .lidljson file.
void OpenSlot ()
This function Opens a Open prompt, and opens .lidljson file.
void ClearAll ()
This function clears the soundboard, as if it was just opened without any file.
void OpenEXPSounboard ()
This function allows the opening of .json files written by EXP Soundboard.
void HelpGuide ()
This function will open the application tour guide.
void HelpAbout ()
This function will open the about window.
void ToolClearShortcut ()
This function will clear all the shortcuts in the soundboard.
void DealDragAndDrop (int)
This function deals with drag and drop in the view, or at least, attempts to.
void SwapWrappers (int firstRow, int secondRow)
This function swaps two soundwrappers in the view.
void SetStatusTextEditText (QString)
This function set the text of the permanent widget in the status bar.
void PostConstruction ()
PostConstruction is called after the mainUI is done constructing forsenE.
void SetUpRecentMenu ()
This function sets up the recent menu.
void CheckForUpdates ()
This function check for updates.
void resizeEvent (QResizeEvent *event)
This function is called whenever the window is resized, and just resizerowstocontent(). And call refreshView()
void dragEnterEvent (QDragEnterEvent *e)
This function checks for the MIME type of files being dragged onto the sounboard.
void dropEvent (QDropEvent *e)
This function checks for the MIME type of files being dragged onto the sounboard.
void ProfileSwitched (QVector< std::shared_ptr< SoundWrapper > > wrappers)
ProfileSwitched.
Signals
void lidlJsonDetected (QFileInfo)
Signal to be emitted whenever a file is saved or opened. So that it appears in the recent menu.
void SaveSoundboardState ()
Signal to be emitted whenever a file is saved or opened. So that its save can be saved and compared to the "ending" state, so modifications can be detected.
void OnConstructionDone ()
Public Member Functions
SoundboardMainUI (QWidget *parent=nullptr)
SoundboardMainUI Default constructor.
Private Member Functions
void fetchDeviceList (QComboBox *comboBox, QAudio::Mode mode=QAudio::AudioOutput)
This function fetches the devices list, and sets up the given combo box.
void setUpMenu ()
This function adds all the entries of the QMenuBar.
void closeEvent (QCloseEvent *event)
This function adds all the entries of the QMenuBar.(Reimplementation of the QMainWindow close event).
void Open (QString fileName)
This function Open a saved soundboard and add all the entries in the CustomTableView.
void HelpShowFirstUserDialog ()
This function construct and display the first-time user dialog.
void refreshView ()
This function deals with editing the data that will be displayed according to user settings. (Read: kind of delegate).
void addSeveralSounds (QVector< SoundWrapper * > sounds, int maximum)
addSeveralSounds Function used by the thread created when opening a lidljson file.
Private Attributes
QVector< std::shared_ptr< SoundWrapper > > _sounds
QVector< QKeySequence > _keySequence
QVector< unsigned int > _keyVirtualKey
QVector< int > _winShorcutHandle
QGridLayout * _gLayout
CustomTableModel * _model
QVector< QList< QStandardItem * > > _data
QVector< QList< QStandardItem * > > _displayedData
QVector< QAction * > _actions
CustomTableView * resultView
GameSelector * _gameSelector
QPushButton * _btnAdd
QPushButton * _btnDelete
QPushButton * _btnEdit
QPushButton * _btnStop
QLabel * _label1
QComboBox * _deviceListOutput
QLabel * _label2
QComboBox * _deviceListVAC
QLabel * _label3
QPushButton * _btnMicInjection
QLabel * _label4
CustomShortcutEdit * _shortcutEditPTT
QPushButton * _btnClearPTT
QLabel * _label5
CustomShortcutEdit * _shortcutEditStop
QPushButton * _btnClearStop
QPushButton * _btnRadialSettings
WrapperProperties * _propertiesWindow
int lastSelectedRow
QTextEdit * _statusEdit
QString _saveName
QMenu * _openRecentMenu
bool _updateScheduled
QWidget * _guideWidget
Ui::Guide * _guideUI
LoadingWidget * _loadingWidget
Detailed Description
Inherits QMainWindow.
Deals with displaying sounds (main UUI) and intercepting shortcuts.
Constructor & Destructor Documentation
SoundboardMainUI()
SoundboardMainUI::SoundboardMainUI (QWidget * parent = nullptr) explicit
SoundboardMainUI Default constructor.
Parameters
parent
References _btnAdd, _btnClearPTT, _btnClearStop, _btnDelete, _btnEdit, _btnMicInjection, _btnRadialSettings, _btnStop, _data, _deviceListOutput, _deviceListVAC, _gameSelector, _gLayout, _keySequence, _keyVirtualKey, _label1, _label2, _label3, _label4, _label5, _model, _propertiesWindow, _saveName, _shortcutEditPTT, _shortcutEditStop, _sounds, _statusEdit, _updateScheduled, _winShorcutHandle, LIDL::Controller::SettingsController::addFileToRecent(), LIDL::Controller::ProfileController::AddProfile(), addSound(), LIDL::Controller::ProfileController::AddSoundsToMainUI(), WrapperProperties::closed(), DealDragAndDrop(), CustomTableView::disableButtons(), editSoundDialog(), CustomTableView::enableButtons(), fetchDeviceList(), GenerateGlobalShortcuts(), GenerateSaveFile(), LIDL::Controller::ProfileController::GetActiveProfile(), LIDL::Controller::HookController::GetInstance(), LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::ProfileController::GetInstance(), lastSelectedRow, lidlJsonDetected(), OnConstructionDone(), PostConstruction(), ProfileSwitched(), LIDL::Controller::SettingsController::RecentFilesChanged(), GameSelector::RefreshWrappers(), Profile::RemoveSoundFromSharedPtr(), resultView, SaveSoundboardState(), LIDL::Controller::SettingsController::SaveState(), CustomShortcutEdit::scanCodeChanged(), LIDL::Controller::HookController::SetHooks(), Profile::SetPttKeySequence(), Profile::SetPttScanCode(), Profile::SetPttVirtualKey(), SetStatusTextEditText(), setStopShortcut(), LIDL::Controller::SettingsController::SettingsChanged(), setUpMenu(), SetUpRecentMenu(), WrapperProperties::signalAddDone(), LIDL::Controller::SettingsController::unHoldPTT(), VER_STRING, and CustomShortcutEdit::virtualKeyChanged().
Member Function Documentation
addSeveralSounds()
void SoundboardMainUI::addSeveralSounds (QVector< SoundWrapper * > sounds, int maximum) private
addSeveralSounds Function used by the thread created when opening a lidljson file.
This function will fix the size of the soundboard. Shows the progress bar. Creates a new thread to deal with the _sounds argument and populate the needed variables. Creates a new thread to handle the displaying of the progress bar (updating current value). This second thread use a worker to have more control over its signal. Then, it will close the widget, delete the pointer, refresh the view and generate shorcuts. Finally, it will enable the UI and save the soundboard state.
Parameters
sounds The sounds array.
maximum The number of file in the sounds variable. (needed for display purposes).
References LIDL::Controller::ProfileController::GetInstance(), and LIDL::Controller::ProfileController::ManualGameConfigurationChanged().
Referenced by Open().
addSound
void SoundboardMainUI::addSound (std::shared_ptr< SoundWrapper > modifiedSound, int whereToInsert = -1, bool generateShortcuts = true, bool refreshView = true) slot
This function add a soundwrapper to the main UI display, and adds/modify the entries in the private members so that the said wrapper can be played.
Parameters
modifiedSound The added sounded/modified sound.
whereToInsert The spot where to insert the sound (only used when it's a sound being edited. Else if it's -1 we insert it at the bottom.
generationMode Should the shortcut be registered or not. Useful when adding a bunch of soundswrapper (opening a soundboard).
References _data, _keySequence, _keyVirtualKey, _sounds, _winShorcutHandle, Profile::AddSound(), SoundWrapper::ErrorPlaying(), GenerateGlobalShortcuts(), LIDL::Controller::ProfileController::GetActiveProfile(), LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::ProfileController::GetInstance(), Profile::GetName(), LIDL::Controller::SettingsController::holdPTT(), SoundWrapper::holdPTTProxy(), SoundWrapper::NowPlaying(), refreshView(), resultView, SetStatusTextEditText(), Profile::SwapSound(), and SoundWrapper::UnexistantFile().
Referenced by dropEvent(), editSoundDialog(), OpenEXPSounboard(), ProfileSwitched(), SoundboardMainUI(), SwapWrappers(), and ToolClearShortcut().
CheckForUpdates
void SoundboardMainUI::CheckForUpdates () slot
This function check for updates.
Check for updates by launching the maintenance tool in the background. If no data => no updates. If data => Ask for user if he wants to update now or later. The updates is stored on a github repository.
References _actions, _updateScheduled, and SetStatusTextEditText().
Referenced by setUpMenu().
ClearAll
void SoundboardMainUI::ClearAll () slot
This function clears the soundboard, as if it was just opened without any file.
Call a function from the controller settings to prompt for save, clears the soundwrapper array, unregisters the shortcuts and clear their array, clears the model, clears the data, clears the devices lists, and finally refreshes the view.
References _data, _deviceListOutput, _deviceListVAC, _displayedData, _keySequence, _keyVirtualKey, _model, _saveName, _shortcutEditPTT, _shortcutEditStop, _sounds, _winShorcutHandle, and refreshView().
Referenced by Open(), OpenEXPSounboard(), PostConstruction(), ProfileSwitched(), and setUpMenu().
closeEvent()
void SoundboardMainUI::closeEvent (QCloseEvent * event) private
This function adds all the entries of the QMenuBar.(Reimplementation of the QMainWindow close event).
Parameters
event Pointer to the event (automatically called).
References _updateScheduled, _winShorcutHandle, GenerateSaveFile(), LIDL::Controller::HookController::GetInstance(), LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::ProfileController::GetInstance(), Save(), LIDL::Controller::SettingsController::SaveSettings(), and LIDL::Controller::HookController::UnSetHooks().
DealDragAndDrop
void SoundboardMainUI::DealDragAndDrop (int newPlace) slot
This function deals with drag and drop in the view, or at least, attempts to.
This function will call SwapWrappers with the correct argument is it detects correct argument. I'm not sure it works correctly forsenD
References resultView, and SwapWrappers().
Referenced by SoundboardMainUI().
dragEnterEvent
void SoundboardMainUI::dragEnterEvent (QDragEnterEvent * e) slot
This function checks for the MIME type of files being dragged onto the sounboard.
If the mime types of the files being dropped are all contained in the settings controller mime types, we accept the event. If one of them isn't, we refuse. If it is a .lidljson file, we accept aswell. Refusing an event will show the icon instead of the + one.
References LIDL::Controller::SettingsController::GetInstance().
dropEvent
void SoundboardMainUI::dropEvent (QDropEvent * e) slot
This function checks for the MIME type of files being dragged onto the sounboard.
This function deals with accepted events from the dragEnterEvent. If it is sound file(s) it will add them to the soundboard based on the settings found inside the controller. If it is a lidljson file, it will open it.
References _deviceListOutput, _deviceListVAC, addSound(), LIDL::SFX::flags, LIDL::Controller::SettingsController::GetDragAndDropSeveralWrappers(), LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::SettingsController::GetSupportedMimeTypes(), LIDL::NONE, Open(), LIDL::Sequential, and LIDL::Singleton.
editSoundDialog
void SoundboardMainUI::editSoundDialog () slot
This function opens the Sound Entry Editor to open the selected sound. It is used by both the EDIT button and the DoubleClicked signal in the view.
References _deviceListOutput, _deviceListVAC, _propertiesWindow, _sounds, addSound(), WrapperProperties::closed(), lastSelectedRow, and WrapperProperties::signalEditDone().
Referenced by SoundboardMainUI().
fetchDeviceList()
void SoundboardMainUI::fetchDeviceList (QComboBox * comboBox, QAudio::Mode mode = QAudio::AudioOutput) private
This function fetches the devices list, and sets up the given combo box.
Parameters
comboBox Pointer to the combo box that will display devices.
mode Deprecated. Defaults to QAudio::AudioOutput.
References BASS_DEVICE_ENABLED, BASS_GetDeviceInfo(), BASS_RecordGetDeviceInfo(), BASS_DEVICEINFO::flags, and BASS_DEVICEINFO::name.
Referenced by setUpMenu(), and SoundboardMainUI().
GenerateGlobalShortcuts
void SoundboardMainUI::GenerateGlobalShortcuts () slot
Function to register all the Shortcuts being used by the LIDL Soundboard.
It will unregister all existing Shortcuts, and register them again.
References _keySequence, _keyVirtualKey, _winShorcutHandle, MOD_ALT, and MOD_CONTROL.
Referenced by addSound(), setUpMenu(), SoundboardMainUI(), and ToolClearShortcut().
GenerateSaveFile
QJsonObject * SoundboardMainUI::GenerateSaveFile () slot
Function to generate the .lidljson save file.
It is used to save the active soundboard. It is also used to detect any modification by comparing the QJsonObject store inside the settings controller with a freshly generated one.
Returns
QJSonObject* (pointer) containing the data.
References _deviceListOutput, _deviceListVAC, _shortcutEditPTT, _shortcutEditStop, _sounds, LIDL::Controller::SettingsController::GetInstance(), CustomShortcutEdit::getScanCode(), CustomShortcutEdit::getText(), CustomShortcutEdit::getVirtualKey(), and VER_STRING.
Referenced by closeEvent(), Open(), OpenEXPSounboard(), PostConstruction(), Save(), SaveAs(), SetStatusTextEditText(), setUpMenu(), and SoundboardMainUI().
HelpAbout
void SoundboardMainUI::HelpAbout () slot
This function will open the about window.
Shows some text about the soundboard, version number, compilation time and compiler, and link to git.
References VER_STRING.
Referenced by setUpMenu().
HelpGuide
void SoundboardMainUI::HelpGuide () slot
This function will open the application tour guide.
Adds a widget to the right of the view, guiding user through every element.
References _btnAdd, _btnClearPTT, _btnClearStop, _btnDelete, _btnEdit, _btnMicInjection, _btnStop, _deviceListOutput, _deviceListVAC, _gLayout, _guideUI, _guideWidget, _shortcutEditPTT, _shortcutEditStop, and resultView.
Referenced by setUpMenu().
HelpShowFirstUserDialog()
void SoundboardMainUI::HelpShowFirstUserDialog () private
This function construct and display the first-time user dialog.
References VER_STRING.
Referenced by PostConstruction(), and setUpMenu().
lidlJsonDetected
void SoundboardMainUI::lidlJsonDetected (QFileInfo) signal
Signal to be emitted whenever a file is saved or opened. So that it appears in the recent menu.
Referenced by Open(), SaveAs(), and SoundboardMainUI().
OnConstructionDone
void SoundboardMainUI::OnConstructionDone () signal
Referenced by SoundboardMainUI().
Open()
void SoundboardMainUI::Open (QString fileName) private
This function Open a saved soundboard and add all the entries in the CustomTableView.
Parameters
fileName String containing the file path.
References _actions, _deviceListOutput, _deviceListVAC, _saveName, _shortcutEditPTT, _shortcutEditStop, addSeveralSounds(), LIDL::Controller::SettingsController::addShowFlag(), LIDL::SFX::chorus, ClearAll(), LIDL::SFX::compressor, LIDL::SFX::distortion, BASS_DX8_GARGLE::dwRateHz, BASS_DX8_GARGLE::dwWaveShape, LIDL::SFX::echo, BASS_DX8_COMPRESSOR::fAttack, BASS_DX8_CHORUS::fDelay, BASS_DX8_FLANGER::fDelay, BASS_DX8_CHORUS::fDepth, BASS_DX8_FLANGER::fDepth, BASS_DX8_DISTORTION::fEdge, BASS_DX8_CHORUS::fFeedback, BASS_DX8_ECHO::fFeedback, BASS_DX8_FLANGER::fFeedback, BASS_DX8_CHORUS::fFrequency, BASS_DX8_FLANGER::fFrequency, BASS_DX8_COMPRESSOR::fGain, BASS_DX8_DISTORTION::fGain, LIDL::SFX::flags, LIDL::SFX::flanger, BASS_DX8_ECHO::fLeftDelay, BASS_DX8_DISTORTION::fPostEQBandwidth, BASS_DX8_DISTORTION::fPostEQCenterFrequency, BASS_DX8_COMPRESSOR::fPredelay, BASS_DX8_DISTORTION::fPreLowpassCutoff, BASS_DX8_COMPRESSOR::fRatio, BASS_DX8_COMPRESSOR::fRelease, BASS_DX8_ECHO::fRightDelay, BASS_DX8_COMPRESSOR::fThreshold, BASS_DX8_CHORUS::fWetDryMix, BASS_DX8_ECHO::fWetDryMix, LIDL::SFX::gargle, GenerateSaveFile(), LIDL::Controller::SettingsController::GetDefaultMainVolume(), LIDL::Controller::SettingsController::GetDefaultVacVolume(), LIDL::Controller::SettingsController::GetInstance(), lidlJsonDetected(), BASS_DX8_ECHO::lPanDelay, BASS_DX8_CHORUS::lPhase, BASS_DX8_FLANGER::lPhase, BASS_DX8_CHORUS::lWaveform, BASS_DX8_FLANGER::lWaveform, Save(), SaveSoundboardState(), LIDL::Sequential, CustomShortcutEdit::setScanCode(), setStopShortcut(), CustomShortcutEdit::setVirtualKey(), LIDL::SHOW_SFX, LIDL::Singleton, and LIDL::WRAP_SONG_LIST.
Referenced by dropEvent(), OpenSlot(), PostConstruction(), and SetUpRecentMenu().
OpenEXPSounboard
void SoundboardMainUI::OpenEXPSounboard () slot
This function allows the opening of .json files written by EXP Soundboard.
References _deviceListOutput, _deviceListVAC, addSound(), ClearAll(), GenerateSaveFile(), LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::ProfileController::GetInstance(), LIDL::Controller::ProfileController::ManualGameConfigurationChanged(), Save(), and LIDL::Sequential.
Referenced by setUpMenu().
OpenSlot
void SoundboardMainUI::OpenSlot () slot
This function Opens a Open prompt, and opens .lidljson file.
It parses the Json contained the file, and add all the settings and wrappers found inside it.
References LIDL::Controller::SettingsController::GetInstance(), and Open().
Referenced by setUpMenu().
PostConstruction
void SoundboardMainUI::PostConstruction () slot
PostConstruction is called after the mainUI is done constructing forsenE.
References ClearAll(), GenerateSaveFile(), LIDL::Controller::SettingsController::GetInstance(), HelpShowFirstUserDialog(), Open(), and LIDL::Controller::SettingsController::SaveState().
Referenced by SoundboardMainUI().
ProfileSwitched
void SoundboardMainUI::ProfileSwitched (QVector< std::shared_ptr< SoundWrapper > > wrappers) slot
ProfileSwitched.
Parameters
wrappers Slot that will be called whenever the profile is switched. It will delete the shared_ptr of mainUI and replace it with the one from the profile. Ref count should be ok :) It will also register the new PTT key to auto-hold and the new sounds shortcuts
References _deviceListOutput, _deviceListVAC, _shortcutEditPTT, _shortcutEditStop, addSound(), ClearAll(), LIDL::Controller::ProfileController::GetInstance(), CustomShortcutEdit::getScanCode(), CustomShortcutEdit::getVirtualKey(), CustomShortcutEdit::setScanCode(), setStopShortcut(), and CustomShortcutEdit::setVirtualKey().
Referenced by SoundboardMainUI().
refreshView()
void SoundboardMainUI::refreshView () private
This function deals with editing the data that will be displayed according to user settings. (Read: kind of delegate).
<UI for the guide/app tour.
References _data, _displayedData, _model, LIDL::Controller::SettingsController::checkShowFlags(), LIDL::Controller::SettingsController::GetInstance(), resultView, LIDL::SHOW_SFX, and LIDL::WRAP_SONG_LIST.
Referenced by addSound(), ClearAll(), resizeEvent(), setUpMenu(), and ToolClearShortcut().
resizeEvent
void SoundboardMainUI::resizeEvent (QResizeEvent * event) slot
This function is called whenever the window is resized, and just resizerowstocontent(). And call refreshView()
References refreshView(), and resultView.
Save
void SoundboardMainUI::Save () slot
Function save the active lidljson file. If no file is already set, it will open the Save As prompt.
References _saveName, GenerateSaveFile(), SaveAs(), SaveSoundboardState(), and SetStatusTextEditText().
Referenced by closeEvent(), Open(), OpenEXPSounboard(), and setUpMenu().
SaveAs
void SoundboardMainUI::SaveAs () slot
This function Opens a Save As prompt, and save the active soundboard as a .lidljson file.
References _saveName, GenerateSaveFile(), LIDL::Controller::SaveController::GetInstance(), LIDL::Controller::SettingsController::GetInstance(), lidlJsonDetected(), SaveSoundboardState(), SetStatusTextEditText(), and LIDL::Controller::SaveController::WriteSaveFile().
Referenced by Save(), and setUpMenu().
SaveSoundboardState
void SoundboardMainUI::SaveSoundboardState () signal
Signal to be emitted whenever a file is saved or opened. So that its save can be saved and compared to the "ending" state, so modifications can be detected.
Referenced by Open(), Save(), SaveAs(), setUpMenu(), and SoundboardMainUI().
SetStatusTextEditText
void SoundboardMainUI::SetStatusTextEditText (QString text) slot
This function set the text of the permanent widget in the status bar.
Will probably be removed at some point.
References _saveName, _statusEdit, GenerateSaveFile(), and LIDL::Controller::SettingsController::GetInstance().
Referenced by addSound(), CheckForUpdates(), Save(), SaveAs(), setUpMenu(), SoundboardMainUI(), and ToolClearShortcut().
setStopShortcut
void SoundboardMainUI::setStopShortcut (unsigned int virtualKey) slot
Function to register the Stop ALL Shortcut. It is used by the associated CustomShortcutEdit and the Open soundboard function.
Referenced by Open(), ProfileSwitched(), and SoundboardMainUI().
setUpMenu()
void SoundboardMainUI::setUpMenu () private
This function adds all the entries of the QMenuBar.
References _actions, _deviceListOutput, _deviceListVAC, _openRecentMenu, LIDL::Controller::SettingsController::addShowFlag(), CheckForUpdates(), ClearAll(), fetchDeviceList(), GenerateGlobalShortcuts(), GenerateSaveFile(), LIDL::Controller::SettingsController::GetInstance(), HelpAbout(), HelpGuide(), HelpShowFirstUserDialog(), OpenEXPSounboard(), OpenSlot(), refreshView(), LIDL::Controller::SettingsController::removeShowFlag(), Save(), SaveAs(), SaveSoundboardState(), SetStatusTextEditText(), LIDL::SHOW_SFX, ToolClearShortcut(), and LIDL::WRAP_SONG_LIST.
Referenced by SoundboardMainUI().
SetUpRecentMenu
void SoundboardMainUI::SetUpRecentMenu () slot
This function sets up the recent menu.
Just add the necessaries entry in the recent menu.
References _openRecentMenu, LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::SettingsController::GetRecentFilesCount(), and Open().
Referenced by SoundboardMainUI().
SwapWrappers
void SoundboardMainUI::SwapWrappers (int firstRow, int secondRow) slot
This function swaps two soundwrappers in the view.
Will copy the both the wrappers and insert them at the index of the other one. It updates the _data and the _sounds arrays since we use the addSound method. The _displayedData array will also be updated, because AddSound calls refreshView().
References _sounds, addSound(), SoundWrapper::getKeySequence(), SoundWrapper::getMainDevice(), SoundWrapper::getPlayMode(), SoundWrapper::getShortcutVirtualKey(), SoundWrapper::getSoundList(), and SoundWrapper::getVacDevice().
Referenced by DealDragAndDrop().
ToolClearShortcut
void SoundboardMainUI::ToolClearShortcut () slot
This function will clear all the shortcuts in the soundboard.
Will unregister all shortcuts. Clears the _data array. Replaced the wrappers in _sounds array by freshly created one without shortcuts. It will alos update the view in the process.
References _data, _keySequence, _model, _sounds, _winShorcutHandle, addSound(), GenerateGlobalShortcuts(), refreshView(), and SetStatusTextEditText().
Referenced by setUpMenu().
winHotKeyPressed
void SoundboardMainUI::winHotKeyPressed (int handle) slot
Function to deal with Shortcut being pressed.
This function will check if the shortcut being processed is the stop key If it is, it tells the controller to un-hold the ptt and stops all running sounds. If it is not, it plays the sound associated with the shortcut.
This function is called by the event loop declared in main.cpp. The shortcut arrays and the soundswrapper array uses the same index.
Parameters
handle The index of the shortcut being played.
References _sounds, LIDL::Controller::SettingsController::GetInstance(), LIDL::Controller::SettingsController::isEditing(), and LIDL::Controller::SettingsController::unHoldPTT().
Referenced by main().
Member Data Documentation
_actions
QVector<QAction*> SoundboardMainUI::_actions private
List of the actions in the MenuBar.
Referenced by CheckForUpdates(), Open(), and setUpMenu().
_btnAdd
QPushButton* SoundboardMainUI::_btnAdd private
Add SoundWrapper button.
Referenced by HelpGuide(), and SoundboardMainUI().
_btnClearPTT
QPushButton* SoundboardMainUI::_btnClearPTT private
Button to unregister and clear the auto-PTT hotkey.
Referenced by HelpGuide(), and SoundboardMainUI().
_btnClearStop
QPushButton* SoundboardMainUI::_btnClearStop private
Button to unregister and clear the Stop All hotkey.
Referenced by HelpGuide(), and SoundboardMainUI().
_btnDelete
QPushButton* SoundboardMainUI::_btnDelete private
Delete SoundWrapper button.
Referenced by HelpGuide(), and SoundboardMainUI().
_btnEdit
QPushButton* SoundboardMainUI::_btnEdit private
Edit SoundWrapper button/*/ QPushButton * _btnPlay; /*!< Play the SoundWrapper according to its playback mode button.
Referenced by HelpGuide(), and SoundboardMainUI().
_btnMicInjection
QPushButton* SoundboardMainUI::_btnMicInjection private
Button that opens the windows sound settings.
Referenced by HelpGuide(), and SoundboardMainUI().
_btnRadialSettings
QPushButton* SoundboardMainUI::_btnRadialSettings private
Referenced by SoundboardMainUI().
_btnStop
QPushButton* SoundboardMainUI::_btnStop private
Delete SoundWrapper button.
Referenced by HelpGuide(), and SoundboardMainUI().
_data
QVector<QList< QStandardItem* > > SoundboardMainUI::_data private
ALL the data recieved by using GetSoundAsItem method.
Referenced by addSound(), ClearAll(), refreshView(), SoundboardMainUI(), and ToolClearShortcut().
_deviceListOutput
QComboBox* SoundboardMainUI::_deviceListOutput private
Contains the actual output device list.
Referenced by ClearAll(), dropEvent(), editSoundDialog(), GenerateSaveFile(), HelpGuide(), Open(), OpenEXPSounboard(), ProfileSwitched(), setUpMenu(), and SoundboardMainUI().
_deviceListVAC
QComboBox* SoundboardMainUI::_deviceListVAC private
Contains the actual VAC output device list.
Referenced by ClearAll(), dropEvent(), editSoundDialog(), GenerateSaveFile(), HelpGuide(), Open(), OpenEXPSounboard(), ProfileSwitched(), setUpMenu(), and SoundboardMainUI().
_displayedData
QVector<QList< QStandardItem* > > SoundboardMainUI::_displayedData private
Processed data according to the user settings.
Referenced by ClearAll(), and refreshView().
_gameSelector
GameSelector* SoundboardMainUI::_gameSelector private
Referenced by SoundboardMainUI().
_gLayout
QGridLayout* SoundboardMainUI::_gLayout private
A grid layout: everything is inside it.
Referenced by HelpGuide(), and SoundboardMainUI().
_guideUI
Ui::Guide* SoundboardMainUI::_guideUI private
<Widget for the guide/app tour.
Referenced by HelpGuide().
_guideWidget
QWidget* SoundboardMainUI::_guideWidget private
Referenced by HelpGuide().
_keySequence
QVector<QKeySequence> SoundboardMainUI::_keySequence private
keySequence array: contains the shortcuts to the sounds (mostly for displaying).
Referenced by addSound(), ClearAll(), GenerateGlobalShortcuts(), SoundboardMainUI(), and ToolClearShortcut().
_keyVirtualKey
QVector<unsigned int> SoundboardMainUI::_keyVirtualKey private
keyVirtualKey array: contains virtual code of the shortcuts to play (to register them).
Referenced by addSound(), ClearAll(), GenerateGlobalShortcuts(), and SoundboardMainUI().
_label1
QLabel* SoundboardMainUI::_label1 private
Label for the main output device list.
Referenced by SoundboardMainUI().
_label2
QLabel* SoundboardMainUI::_label2 private
Label for the VAC output device list.
Referenced by SoundboardMainUI().
_label3
QLabel* SoundboardMainUI::_label3 private
Label for microphone injection.
Referenced by SoundboardMainUI().
_label4
QLabel* SoundboardMainUI::_label4 private
Label for the Auto-Hold PTT feature.
Referenced by SoundboardMainUI().
_label5
QLabel* SoundboardMainUI::_label5 private
Label for the stop all feature.
Referenced by SoundboardMainUI().
_loadingWidget
LoadingWidget* SoundboardMainUI::_loadingWidget private
Widget that shows the loading bar.
_model
CustomTableModel* SoundboardMainUI::_model private
Custom model that contains the data being displayed.
Referenced by ClearAll(), refreshView(), SoundboardMainUI(), and ToolClearShortcut().
_openRecentMenu
QMenu* SoundboardMainUI::_openRecentMenu private
QMenu containing the recently opened lidljson
Referenced by setUpMenu(), and SetUpRecentMenu().
_propertiesWindow
WrapperProperties* SoundboardMainUI::_propertiesWindow private
Window that handle wrapper edition.
Referenced by editSoundDialog(), and SoundboardMainUI().
_saveName
QString SoundboardMainUI::_saveName private
Keeps tracks the .lidljson file being read/written.
Referenced by ClearAll(), Open(), Save(), SaveAs(), SetStatusTextEditText(), and SoundboardMainUI().
_shortcutEditPTT
CustomShortcutEdit* SoundboardMainUI::_shortcutEditPTT private
CustomShortcutEdit field to set the microphone injection hotkey.
Referenced by ClearAll(), GenerateSaveFile(), HelpGuide(), Open(), ProfileSwitched(), and SoundboardMainUI().
_shortcutEditStop
CustomShortcutEdit* SoundboardMainUI::_shortcutEditStop private
CustomShortcutEdit field to set the stop all hotkey.
Referenced by ClearAll(), GenerateSaveFile(), HelpGuide(), Open(), ProfileSwitched(), and SoundboardMainUI().
_sounds
QVector<std::shared_ptr<SoundWrapper> > SoundboardMainUI::_sounds private
SoundWrapper array: contains the sounds
Referenced by addSound(), ClearAll(), editSoundDialog(), GenerateSaveFile(), SoundboardMainUI(), SwapWrappers(), ToolClearShortcut(), and winHotKeyPressed().
_statusEdit
QTextEdit* SoundboardMainUI::_statusEdit private
Main widget of the QStatusBar so we have more control over it.
Referenced by SetStatusTextEditText(), and SoundboardMainUI().
_updateScheduled
bool SoundboardMainUI::_updateScheduled private
Boolean to know if the user wanna update the soundboard after quitting.
Referenced by CheckForUpdates(), closeEvent(), and SoundboardMainUI().
_winShorcutHandle
QVector<int> SoundboardMainUI::_winShorcutHandle private
Handles to the registered shortcuts.
Referenced by addSound(), ClearAll(), closeEvent(), GenerateGlobalShortcuts(), SoundboardMainUI(), and ToolClearShortcut().
lastSelectedRow
int SoundboardMainUI::lastSelectedRow private
Keeps tracks of last selected rows. (Could probably use a method of QTableView.
Referenced by editSoundDialog(), and SoundboardMainUI().
resultView
CustomTableView* SoundboardMainUI::resultView private
Custom table view (inherists from QTableView) to display the data in the model.
Referenced by addSound(), DealDragAndDrop(), HelpGuide(), refreshView(), resizeEvent(), and SoundboardMainUI().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/soundboardMainUI.h
D:/Qt/Projects/Lidl_Soundboard/soundboardMainUI.cpp