LIDL Soundboard: CustomShortcutEdit Class Reference
CustomShortcutEdit Class Reference
The CustomShortcutEdit class.
#include <CustomShortcutEdit.h>
Public Slots
void sendSignal ()
sendSignal This slot is called whenever the editing is done, could be replaced by lambda but i'm lazy today
Signals
void keyPressed ()
keyPressed
void scanCodeChanged (int)
scanCodeChanged
void virtualKeyChanged (int)
virtualKeyChanged
Public Member Functions
CustomShortcutEdit (QWidget *parent=nullptr)
CustomShortcutEdit.
int getVirtualKey ()
getVirtualKey
int getScanCode ()
getScanCode
QString getText ()
getText
void setVirtualKey (int)
setVirtualKey
void setScanCode (int)
setScanCode
Private Member Functions
void keyPressEvent (QKeyEvent *e)
keyPressEvent
Private Attributes
int _virtualKey
_virtualKey
int _scanCode
_scanCode
Detailed Description
The CustomShortcutEdit class.
Version
1.7.0
Since
0.42
Constructor & Destructor Documentation
CustomShortcutEdit()
CustomShortcutEdit::CustomShortcutEdit (QWidget * parent = nullptr) explicit
CustomShortcutEdit.
Parameters
parent
References _scanCode, _virtualKey, and sendSignal().
Member Function Documentation
getScanCode()
int CustomShortcutEdit::getScanCode ()
getScanCode
Returns
References _scanCode.
Referenced by SoundboardMainUI::GenerateSaveFile(), and SoundboardMainUI::ProfileSwitched().
getText()
QString CustomShortcutEdit::getText ()
getText
Returns
Referenced by SoundboardMainUI::GenerateSaveFile(), and WrapperProperties::WrapperProperties().
getVirtualKey()
int CustomShortcutEdit::getVirtualKey ()
getVirtualKey
Returns
References _virtualKey.
Referenced by SoundboardMainUI::GenerateSaveFile(), SoundboardMainUI::ProfileSwitched(), and WrapperProperties::WrapperProperties().
keyPressed
void CustomShortcutEdit::keyPressed () signal
keyPressed
Referenced by keyPressEvent(), and WrapperProperties::WrapperProperties().
keyPressEvent()
void CustomShortcutEdit::keyPressEvent (QKeyEvent * e) private
keyPressEvent
Parameters
e
References _scanCode, _virtualKey, and keyPressed().
scanCodeChanged
void CustomShortcutEdit::scanCodeChanged (int) signal
scanCodeChanged
Referenced by sendSignal(), setScanCode(), and SoundboardMainUI::SoundboardMainUI().
sendSignal
void CustomShortcutEdit::sendSignal () slot
sendSignal This slot is called whenever the editing is done, could be replaced by lambda but i'm lazy today
References _scanCode, _virtualKey, scanCodeChanged(), and virtualKeyChanged().
Referenced by CustomShortcutEdit().
setScanCode()
void CustomShortcutEdit::setScanCode (int sc)
setScanCode
References _scanCode, and scanCodeChanged().
Referenced by SoundboardMainUI::Open(), and SoundboardMainUI::ProfileSwitched().
setVirtualKey()
void CustomShortcutEdit::setVirtualKey (int vk)
setVirtualKey
References _virtualKey, and virtualKeyChanged().
Referenced by SoundboardMainUI::Open(), SoundboardMainUI::ProfileSwitched(), and WrapperProperties::WrapperProperties().
virtualKeyChanged
void CustomShortcutEdit::virtualKeyChanged (int) signal
virtualKeyChanged
Referenced by sendSignal(), setVirtualKey(), and SoundboardMainUI::SoundboardMainUI().
Member Data Documentation
_scanCode
int CustomShortcutEdit::_scanCode private
_scanCode
Referenced by CustomShortcutEdit(), getScanCode(), keyPressEvent(), sendSignal(), and setScanCode().
_virtualKey
int CustomShortcutEdit::_virtualKey private
_virtualKey
Referenced by CustomShortcutEdit(), getVirtualKey(), keyPressEvent(), sendSignal(), and setVirtualKey().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/CustomShortcutEdit.h
D:/Qt/Projects/Lidl_Soundboard/CustomShortcutEdit.cpp