LIDL Soundboard: Profile Class Reference
Profile Class Reference
The Profile class Describe a profile: Name List of linked executable that will make this profile switched to when the executable is detected List of sounds as a QVector<shared_ptr<SoundWrapper>> The owner ship of those element is shared between the profile and the main ui. So reference count should be like this:
#include <Profile.h>
Classes
class Builder
Public Member Functions
QString GetName () const
GetName.
void SetName (QString newName)
SetName.
QSet< QString > GetGameList () const
GetGameList.
void SwapGames (QSet< QString > newListHYPERBRUH)
SwapGames.
QString GetConfigAsString () const
GetConfig.
bool IsContainingExe (QString exe) const
IsExeHere Search for an executable in _exeList.
QVector< std::shared_ptr< SoundWrapper > > GetSounds () const
GetSounds.
void AddSound (std::shared_ptr< SoundWrapper > wrapper)
AddSound.
void RemoveSoundFromSharedPtr (std::shared_ptr< SoundWrapper > wrapper)
RemoveSoundFromSharedPtr.
void SwapSound (std::shared_ptr< SoundWrapper > oldWrapper, std::shared_ptr< SoundWrapper > newWrapper)
SwapSound.
Profile * GetParent () const
GetParent.
void ClearSounds ()
ClearSounds Remove every sound from the array.
void SetPttScanCode (int sc)
SetPttScanCode.
void SetPttVirtualKey (int vk)
SetPttVirtualKey.
int GetPttScanCode () const
GetPttScanCode.
int GetPttVirtualKey () const
GetPttVirtualKey.
void SetPttKeySequence (QKeySequence sequence)
SetPttKeySequence.
QKeySequence GetPttKeySequence () const
SetPttKeySequence.
QJsonObject GetProfileAsObject () const
GetProfileAsObject.
~Profile ()
Private Member Functions
Profile (QString name, QSet< QString > exe, Profile *parent, QVector< std::shared_ptr< SoundWrapper >> wrappers, int PttVirtualKey, int PttScanCode, QKeySequence PttKeySequence)
Private Attributes
QString _name
QSet< QString > _exeList
Profile * _parent
QVector< std::shared_ptr< SoundWrapper > > _sounds
int _PTTVirtualKey = -1
int _PTTScanCode = -1
QKeySequence _PTTKeySequence
Detailed Description
The Profile class Describe a profile: Name List of linked executable that will make this profile switched to when the executable is detected List of sounds as a QVector<shared_ptr<SoundWrapper>> The owner ship of those element is shared between the profile and the main ui. So reference count should be like this:
1 for the UI (IF profile is currently active)
1 for the profile
1 for which ever profile mirrors it
temporary ones for editing widgets (like editing profiles etc) To see the ref count while in a "still" mode, just play a sound. It will display ref count in qDebug() output.
Constructor & Destructor Documentation
~Profile()
Profile::~Profile ()
References _name, and _sounds.
Profile()
Profile::Profile (QString name, QSet< QString > exe, Profile * parent, QVector< std::shared_ptr< SoundWrapper >> wrappers, int PttVirtualKey, int PttScanCode, QKeySequence PttKeySequence) private
Referenced by Profile::Builder::Build().
Member Function Documentation
AddSound()
void Profile::AddSound (std::shared_ptr< SoundWrapper > wrapper)
AddSound.
Parameters
The wrapper to append to _sounds
References _sounds.
Referenced by LIDL::Controller::ProfileController::AddProfile(), and SoundboardMainUI::addSound().
ClearSounds()
void Profile::ClearSounds ()
ClearSounds Remove every sound from the array.
References _sounds.
Referenced by LIDL::Controller::ProfileController::AutomaticConfigurationChange(), and LIDL::Controller::ProfileController::ManualGameConfigurationChanged().
GetConfigAsString()
QString Profile::GetConfigAsString () const
GetConfig.
Returns
The config as a string, mostly used for debug
References _exeList, and _name.
Referenced by LIDL::Controller::ProfileController::AddProfile().
GetGameList()
QSet< QString > Profile::GetGameList () const
GetGameList.
Returns
The game list as a QSet<QString>
References _exeList.
Referenced by ProfileEdit::ProfileEdit().
GetName()
QString Profile::GetName () const
GetName.
Returns
Profile name as a QString
References _name.
Referenced by LIDL::Controller::ProfileController::AddProfile(), SoundboardMainUI::addSound(), LIDL::Controller::ProfileController::AutomaticConfigurationChange(), LIDL::Controller::ProfileController::DeleteActiveProfile(), GetProfileAsObject(), ProfileEdit::ProfileEdit(), GameSelector::RefreshProfiles(), LIDL::OverlayController::ShowGameOverlay(), and LIDL::Callback::ShowOverlay().
GetParent()
Profile * Profile::GetParent () const
GetParent.
Returns
The parent profile that sound should be mirrored from
References _parent.
Referenced by LIDL::Controller::ProfileController::AutomaticConfigurationChange(), and LIDL::Controller::ProfileController::ManualGameConfigurationChanged().
GetProfileAsObject()
QJsonObject Profile::GetProfileAsObject () const
GetProfileAsObject.
Returns
A JSON Object representing this profile
References _exeList, _name, _parent, _PTTKeySequence, _PTTScanCode, _PTTVirtualKey, _sounds, and GetName().
GetPttKeySequence()
QKeySequence Profile::GetPttKeySequence () const
SetPttKeySequence.
Parameters
sequence Gets this profile Push To Talk QKeySequence
References _PTTKeySequence.
Referenced by LIDL::Controller::ProfileController::AddProfile().
GetPttScanCode()
int Profile::GetPttScanCode () const
GetPttScanCode.
Returns
Gets this profile Push To Talk Scan Code
References _PTTScanCode.
Referenced by LIDL::Controller::ProfileController::AddProfile(), and LIDL::Controller::SettingsController::holdPTT().
GetPttVirtualKey()
int Profile::GetPttVirtualKey () const
GetPttVirtualKey.
Returns
Gets this profile Push To Talk Virtual Key
References _PTTVirtualKey.
Referenced by LIDL::Controller::ProfileController::AddProfile(), and LIDL::Controller::SettingsController::holdPTT().
GetSounds()
QVector< std::shared_ptr< SoundWrapper > > Profile::GetSounds () const
GetSounds.
Returns
The sounds associated with this profile
References _sounds.
Referenced by LIDL::Controller::ProfileController::AddProfile(), LIDL::Controller::ProfileController::AutomaticConfigurationChange(), and LIDL::Controller::ProfileController::ManualGameConfigurationChanged().
IsContainingExe()
bool Profile::IsContainingExe (QString exe) const
IsExeHere Search for an executable in _exeList.
Returns
true is found, false otherwise
References _exeList.
RemoveSoundFromSharedPtr()
void Profile::RemoveSoundFromSharedPtr (std::shared_ptr< SoundWrapper > wrapper)
RemoveSoundFromSharedPtr.
Parameters
wrapper a shared_ptr
Will remove a shared_ptr from the QVector (when the sound was deleted or replaced in the main UI)
References _sounds.
Referenced by SoundboardMainUI::SoundboardMainUI().
SetName()
void Profile::SetName (QString newName)
SetName.
Parameters
newName Set the name, useful when editing profiles.
References _name.
SetPttKeySequence()
void Profile::SetPttKeySequence (QKeySequence sequence)
SetPttKeySequence.
Parameters
sequence Sets this profile Push To Talk QKeySequence
References _PTTKeySequence.
Referenced by LIDL::Controller::ProfileController::AddProfile(), and SoundboardMainUI::SoundboardMainUI().
SetPttScanCode()
void Profile::SetPttScanCode (int sc)
SetPttScanCode.
Parameters
sc Sets this profile Push To Talk Scan Code
References _PTTScanCode.
Referenced by LIDL::Controller::ProfileController::AddProfile(), and SoundboardMainUI::SoundboardMainUI().
SetPttVirtualKey()
void Profile::SetPttVirtualKey (int vk)
SetPttVirtualKey.
Parameters
vk Set this profile Push To Talk Virtual Key
References _PTTVirtualKey.
Referenced by LIDL::Controller::ProfileController::AddProfile(), and SoundboardMainUI::SoundboardMainUI().
SwapGames()
void Profile::SwapGames (QSet< QString > newListHYPERBRUH)
SwapGames.
Parameters
newListHYPERBRUH Swap the executable list by the new list, useful when edition profiles.
References _exeList.
SwapSound()
void Profile::SwapSound (std::shared_ptr< SoundWrapper > oldWrapper, std::shared_ptr< SoundWrapper > newWrapper)
SwapSound.
Parameters
oldWrapper
newWrapper Will swap oldWrapper by newWrapper using shared_ptr<>::reset() Decreasing ref count of oldWrapper in the proccess
References _sounds.
Referenced by SoundboardMainUI::addSound().
Member Data Documentation
_exeList
QSet<QString> Profile::_exeList private
Array of executables
Referenced by GetConfigAsString(), GetGameList(), GetProfileAsObject(), IsContainingExe(), and SwapGames().
_name
QString Profile::_name private
Referenced by GetConfigAsString(), GetName(), GetProfileAsObject(), SetName(), and ~Profile().
_parent
Profile* Profile::_parent private
Referenced by GetParent(), and GetProfileAsObject().
_PTTKeySequence
QKeySequence Profile::_PTTKeySequence private
Referenced by GetProfileAsObject(), GetPttKeySequence(), and SetPttKeySequence().
_PTTScanCode
int Profile::_PTTScanCode = -1 private
Referenced by GetProfileAsObject(), GetPttScanCode(), and SetPttScanCode().
_PTTVirtualKey
int Profile::_PTTVirtualKey = -1 private
Referenced by GetProfileAsObject(), GetPttVirtualKey(), and SetPttVirtualKey().
_sounds
QVector<std::shared_ptr<SoundWrapper> > Profile::_sounds private
Referenced by AddSound(), ClearSounds(), GetProfileAsObject(), GetSounds(), RemoveSoundFromSharedPtr(), SwapSound(), and ~Profile().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/Profile.h
D:/Qt/Projects/Lidl_Soundboard/source/Profile.cpp