LIDL Soundboard: FramelessWindow Class Reference
FramelessWindow Class Reference
#include <framelesswindow.h>
Public Slots
void setWindowTitle (const QString &text)
void setWindowIcon (const QIcon &ico)
Signals
void windowIconLeftClicked ()
void windowIconRightClicked ()
void windowIconDblClick ()
Public Member Functions
FramelessWindow (QWidget *parent=0)
void setContent (QWidget *w)
Protected Member Functions
virtual void changeEvent (QEvent *event)
Protected Attributes
QHBoxLayout contentLayout
Private Slots
void on_applicationStateChanged (Qt::ApplicationState state)
void on_minimizeButton_clicked ()
void on_restoreButton_clicked ()
void on_maximizeButton_clicked ()
void on_closeButton_clicked ()
void on_windowTitlebar_doubleClicked ()
Private Member Functions
void styleWindow (bool bActive, bool bNoState)
Private Attributes
Ui::FramelessWindow * ui
Constructor & Destructor Documentation
FramelessWindow()
FramelessWindow::FramelessWindow (QWidget * parent = 0) explicit
References MouseButtonSignaler::installOn(), MouseButtonSignaler::mouseButtonEvent(), on_applicationStateChanged(), ui, windowIconDblClick(), windowIconLeftClicked(), and windowIconRightClicked().
Member Function Documentation
changeEvent()
void FramelessWindow::changeEvent (QEvent * event) protected virtual
References on_maximizeButton_clicked(), and on_restoreButton_clicked().
on_applicationStateChanged
void FramelessWindow::on_applicationStateChanged (Qt::ApplicationState state) private slot
References styleWindow().
Referenced by FramelessWindow().
on_closeButton_clicked
void FramelessWindow::on_closeButton_clicked () private slot
on_maximizeButton_clicked
void FramelessWindow::on_maximizeButton_clicked () private slot
References styleWindow(), and ui.
Referenced by changeEvent(), and on_windowTitlebar_doubleClicked().
on_minimizeButton_clicked
void FramelessWindow::on_minimizeButton_clicked () private slot
on_restoreButton_clicked
void FramelessWindow::on_restoreButton_clicked () private slot
References styleWindow(), and ui.
Referenced by changeEvent(), and on_windowTitlebar_doubleClicked().
on_windowTitlebar_doubleClicked
void FramelessWindow::on_windowTitlebar_doubleClicked () private slot
References on_maximizeButton_clicked(), and on_restoreButton_clicked().
setContent()
void FramelessWindow::setContent (QWidget * w)
References contentLayout, and ui.
setWindowIcon
void FramelessWindow::setWindowIcon (const QIcon & ico) slot
References ui.
setWindowTitle
void FramelessWindow::setWindowTitle (const QString & text) slot
References ui.
styleWindow()
void FramelessWindow::styleWindow (bool bActive, bool bNoState) private
References ui.
Referenced by on_applicationStateChanged(), on_maximizeButton_clicked(), and on_restoreButton_clicked().
windowIconDblClick
void FramelessWindow::windowIconDblClick () signal
Referenced by FramelessWindow().
windowIconLeftClicked
void FramelessWindow::windowIconLeftClicked () signal
Referenced by FramelessWindow().
windowIconRightClicked
void FramelessWindow::windowIconRightClicked () signal
Referenced by FramelessWindow().
Member Data Documentation
contentLayout
QHBoxLayout FramelessWindow::contentLayout protected
Referenced by setContent().
ui
Ui::FramelessWindow* FramelessWindow::ui private
Referenced by FramelessWindow(), on_maximizeButton_clicked(), on_restoreButton_clicked(), setContent(), setWindowIcon(), setWindowTitle(), and styleWindow().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/framelesswindow.h
D:/Qt/Projects/Lidl_Soundboard/framelesswindow.cpp