LIDL Soundboard: LIDL::OverlayController Class Reference
LIDL::OverlayController Class Reference
The OverlayController singleton.
#include <OverlayController.h>
Public Member Functions
void ResizeToWindow (HWND hwnd)
Resize the overlay to the topmost window. Should be called whenever topmost window changes, or is resized.
void ShowGameOverlay (HWND hwnd)
Show the smol overlay when topmost window (game) changes.
void ShowGameOverlay (Profile *profile)
ShowGameOverlay.
void SetRadialScanCode (int sc)
SetRadialScanCode.
void SetRadialVirtualKey (int vk)
SetRadialVirtualKey.
Static Public Member Functions
static OverlayController * GetInstance ()
Private Member Functions
OverlayController (QWidget *parent=nullptr)
OverlayController default constructor.
Private Attributes
QTimer * _timerFade
GameNameOverlay * _gameOverlay
QGridLayout * _layout
int _radialScanCode
int _radialVirtualKey
Static Private Attributes
static OverlayController * self = nullptr
Detailed Description
The OverlayController singleton.
smth here
Author
Devolution
Version
1.8.0
Since
1.8.0
Constructor & Destructor Documentation
OverlayController()
LIDL::OverlayController::OverlayController (QWidget * parent = nullptr) explicit private
OverlayController default constructor.
Parameters
parent
References _gameOverlay, _radialScanCode, _radialVirtualKey, and _timerFade.
Referenced by GetInstance().
Member Function Documentation
GetInstance()
OverlayController * LIDL::OverlayController::GetInstance () static
References OverlayController().
Referenced by LIDL::Callback::ResizeToWindow(), and LIDL::Callback::ShowOverlay().
ResizeToWindow()
void LIDL::OverlayController::ResizeToWindow (HWND hwnd)
Resize the overlay to the topmost window. Should be called whenever topmost window changes, or is resized.
Parameters
hwnd a handler to a window
References _gameOverlay.
Referenced by LIDL::Callback::ResizeToWindow(), and LIDL::Callback::ShowOverlay().
SetRadialScanCode()
void LIDL::OverlayController::SetRadialScanCode (int sc)
SetRadialScanCode.
Parameters
sc
References _radialScanCode.
SetRadialVirtualKey()
void LIDL::OverlayController::SetRadialVirtualKey (int vk)
SetRadialVirtualKey.
Parameters
vk
References _radialVirtualKey.
ShowGameOverlay() [1/2]
void LIDL::OverlayController::ShowGameOverlay (HWND hwnd)
Show the smol overlay when topmost window (game) changes.
Parameters
hwnd a handler to a window Will get the name of the window from hwnd.
Deprecated:
References _gameOverlay, _timerFade, GameNameOverlay::FadeOut(), and GameNameOverlay::SetText().
Referenced by LIDL::Callback::ShowOverlay().
ShowGameOverlay() [2/2]
void LIDL::OverlayController::ShowGameOverlay (Profile * profile)
ShowGameOverlay.
Show the smol overlay when topmost window (game) changes.
Parameters
profile Will display profile->name();
References _gameOverlay, _timerFade, GameNameOverlay::FadeOut(), Profile::GetName(), and GameNameOverlay::SetText().
Member Data Documentation
_gameOverlay
GameNameOverlay* LIDL::OverlayController::_gameOverlay private
Main overlay
Referenced by OverlayController(), ResizeToWindow(), and ShowGameOverlay().
_layout
QGridLayout* LIDL::OverlayController::_layout private
The layout
_radialScanCode
int LIDL::OverlayController::_radialScanCode private
Referenced by OverlayController(), and SetRadialScanCode().
_radialVirtualKey
int LIDL::OverlayController::_radialVirtualKey private
Referenced by OverlayController(), and SetRadialVirtualKey().
_timerFade
QTimer* LIDL::OverlayController::_timerFade private
Timer that controls the fade in/out
Referenced by OverlayController(), and ShowGameOverlay().
self
OverlayController * LIDL::OverlayController::self = nullptr static private
A pointer to the only existing OverlayController.
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/OverlayController.h
D:/Qt/Projects/Lidl_Soundboard/source/OverlayController.cpp