LIDL Soundboard: CustomListWidget Class Reference
CustomListWidget Class Reference
The CustomListWidget class : inherits QListWidget.
#include <CustomListWidget.h>
Signals
void fileDragged (QString)
fileDragged Signal to send when a file is dragged onto the view.
Public Member Functions
CustomListWidget (QWidget *parent=nullptr)
CustomListWidget Default constructor.
void dragEnterEvent (QDragEnterEvent *event)
dragEnterEvent To deal with drag and drop events.
void dropEvent (QDropEvent *e)
dropEvent If a dragEnterEvent was accepted, it will end in the dropEvent when release.
Detailed Description
The CustomListWidget class : inherits QListWidget.
Constructor & Destructor Documentation
CustomListWidget()
CustomListWidget::CustomListWidget (QWidget * parent = nullptr) explicit
CustomListWidget Default constructor.
Parameters
parent As usual, the parent.
Member Function Documentation
dragEnterEvent()
void CustomListWidget::dragEnterEvent (QDragEnterEvent * event)
dragEnterEvent To deal with drag and drop events.
We check the event to know if its MIME type are accepted, it it is, we allow the event to continue to dropEvent.
Parameters
event The variable containing the event.
References LIDL::Controller::SettingsController::GetInstance().
dropEvent()
void CustomListWidget::dropEvent (QDropEvent * e)
dropEvent If a dragEnterEvent was accepted, it will end in the dropEvent when release.
Parameters
e The variable containing the event.
References fileDragged().
fileDragged
void CustomListWidget::fileDragged (QString) signal
fileDragged Signal to send when a file is dragged onto the view.
It is intercepted in wrapperproperties.cpp, it will add the file to the wrapper being edited.
Referenced by dropEvent(), and WrapperProperties::WrapperProperties().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/CustomListWidget.h
D:/Qt/Projects/Lidl_Soundboard/source/CustomListWidget.cpp