LIDL Soundboard: LoadingWidgetWorker Class Reference
LoadingWidgetWorker Class Reference
#include <LoadingWidgetWorker.h>
Public Slots
void process ()
Signals
void finished ()
void setValue (int value)
Public Member Functions
LoadingWidgetWorker (QVector< QList< QStandardItem * >> *ptrData, int max, QObject *parent=nullptr)
~LoadingWidgetWorker ()
Private Attributes
QVector< QList< QStandardItem * > > * _ptrData
int _maximum
Constructor & Destructor Documentation
LoadingWidgetWorker()
LoadingWidgetWorker::LoadingWidgetWorker (QVector< QList< QStandardItem * >> * ptrData, int max, QObject * parent = nullptr)
References _maximum, and _ptrData.
~LoadingWidgetWorker()
LoadingWidgetWorker::~LoadingWidgetWorker ()
Member Function Documentation
finished
void LoadingWidgetWorker::finished () signal
Referenced by process().
process
void LoadingWidgetWorker::process () slot
References _maximum, _ptrData, finished(), and setValue().
setValue
void LoadingWidgetWorker::setValue (int value) signal
Referenced by process().
Member Data Documentation
_maximum
int LoadingWidgetWorker::_maximum private
Referenced by LoadingWidgetWorker(), and process().
_ptrData
QVector<QList< QStandardItem* > >* LoadingWidgetWorker::_ptrData private
Referenced by LoadingWidgetWorker(), and process().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/LoadingWidgetWorker.h
D:/Qt/Projects/Lidl_Soundboard/LoadingWidgetWorker.cpp