LIDL Soundboard: CustomTableView Class Reference
CustomTableView Class Reference
#include <CustomTableView.h>
Signals
void disableButtons ()
void enableButtons ()
void hoverIndexChanged (QModelIndex)
Public Member Functions
CustomTableView (QWidget *parent=nullptr)
Private Member Functions
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
void onMouseHover (QEvent *event)
Private Attributes
StyledDelegate * _delegate
int _currentHovered
Constructor & Destructor Documentation
CustomTableView()
CustomTableView::CustomTableView (QWidget * parent = nullptr) explicit
References _delegate, and LIDL::HoverRows.
Member Function Documentation
disableButtons
void CustomTableView::disableButtons () signal
Referenced by selectionChanged(), and SoundboardMainUI::SoundboardMainUI().
enableButtons
void CustomTableView::enableButtons () signal
Referenced by selectionChanged(), and SoundboardMainUI::SoundboardMainUI().
hoverIndexChanged
void CustomTableView::hoverIndexChanged (QModelIndex) signal
onMouseHover()
void CustomTableView::onMouseHover (QEvent * event) private
selectionChanged()
void CustomTableView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) private
References disableButtons(), and enableButtons().
Member Data Documentation
_currentHovered
int CustomTableView::_currentHovered private
_delegate
StyledDelegate* CustomTableView::_delegate private
Referenced by CustomTableView().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/CustomTableView.h
D:/Qt/Projects/Lidl_Soundboard/source/CustomTableView.cpp