LIDL Soundboard: Spoiler Class Reference
Spoiler Class Reference
#include <Spoiler.h>
Public Slots
void Close ()
void Open ()
Signals
void Opened ()
void Closed ()
Public Member Functions
Spoiler (const QString &title="", const int animationDuration=300, QWidget *parent=0)
void setContentLayout (QLayout &contentLayout)
void setContentLayout (QLayout *ptrLayout)
void setTitle (const QString &title)
Private Attributes
QGridLayout mainLayout
QToolButton toggleButton
QFrame headerLine
QParallelAnimationGroup toggleAnimation
QScrollArea contentArea
int animationDuration {300}
Constructor & Destructor Documentation
Spoiler()
Spoiler::Spoiler (const QString & title = "", const int animationDuration = 300, QWidget * parent = 0) explicit
References Closed(), contentArea, headerLine, mainLayout, Opened(), toggleAnimation, and toggleButton.
Member Function Documentation
Close
void Spoiler::Close () slot
References contentArea, and toggleButton.
Referenced by WrapperProperties::WrapperProperties().
Closed
void Spoiler::Closed () signal
Referenced by Spoiler().
Open
void Spoiler::Open () slot
References contentArea, and toggleButton.
Referenced by PresetWizardIntroPage::presetBoxIndexChanged(), PresetWizardIntroPage::radioWasClicked(), and PresetWizardIntroPage::sfxBoxIndexChanged().
Opened
void Spoiler::Opened () signal
Referenced by Spoiler(), and WrapperProperties::WrapperProperties().
setContentLayout() [1/2]
void Spoiler::setContentLayout (QLayout & contentLayout)
References animationDuration, contentArea, and toggleAnimation.
Referenced by PresetWizardIntroPage::addWidgets(), PresetWizardIntroPage::PresetWizardIntroPage(), setContentLayout(), and WrapperProperties::WrapperProperties().
setContentLayout() [2/2]
void Spoiler::setContentLayout (QLayout * ptrLayout)
References setContentLayout().
setTitle()
void Spoiler::setTitle (const QString & title)
References toggleButton.
Member Data Documentation
animationDuration
int Spoiler::animationDuration {300} private
Referenced by setContentLayout().
contentArea
QScrollArea Spoiler::contentArea private
Referenced by Close(), Open(), setContentLayout(), and Spoiler().
headerLine
QFrame Spoiler::headerLine private
Referenced by Spoiler().
mainLayout
QGridLayout Spoiler::mainLayout private
Referenced by Spoiler().
toggleAnimation
QParallelAnimationGroup Spoiler::toggleAnimation private
Referenced by setContentLayout(), and Spoiler().
toggleButton
QToolButton Spoiler::toggleButton private
Referenced by Close(), Open(), setTitle(), and Spoiler().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/Spoiler.h
D:/Qt/Projects/Lidl_Soundboard/source/Spoiler.cpp