LIDL Soundboard: LIDL::Controller::SettingsController Class Reference
LIDL::Controller::SettingsController Class Reference
#include <SettingsController.h>
Public Slots
void SetDefaultMainVolume (int)
SetDefaultMainVolume Sets the default main volume inside the controller, to be used when creating wrappers, and saved in the lidlsettings.
void SetDefaultVacVolume (int)
SetDefaultVacVolume Sets the default VAC volume inside the controller, to be used when creating wrappers, and saved in the lidlsettings.
void SetRecentFileCount (int)
void ShowSettingsWindow ()
void SetPTTScanCode (int sc)
SetPTTScanCode Register the key to be auto-held while playing a sound.
void SetPTTVirtualKey (int vk)
SetPTTVirtualKey Register the key to be auto-held while playing a sound.
void buttonBrowseLidl ()
buttonBrowseLidl Slot connected to a file browser button TODO: refactor as a lambda
void buttonBrowseSound ()
buttonBrowseSound Slot connected to a file browser button TODO: refactor as a lambda
void addFileToRecent (QFileInfo fileInfo)
addFileToRecent
Signals
void RecentFilesChanged ()
RecentFilesChanged Signal is caught by the main UI to changes the Open Recent Menu.
void SettingsChanged ()
void ProfileConfigurationChanged ()
Public Member Functions
int GetDefaultMainVolume () const
GetDefaultMainVolume.
int GetDefaultVacVolume () const
GetDefaultVacVolume.
QString GetDefaultSoundboardFolder () const
GetDefaultSoundboardFolder.
QString GetDefaultSoundFolder () const
GetDefaultSoundFolder.
bool OpenSettings ()
OpenSettings.
void SaveSettings ()
SaveSettings.
QString GetLastOpenedSoundboard ()
GetLastOpenedSoundboard.
std::deque< QFileInfo > GetRecentFiles ()
GetRecentFiles.
int GetRecentFilesCount () const
GetRecentFilesCount.
void SaveState (QJsonObject object)
SaveState.
bool SaveIsDifferentFrom (QJsonObject newObject)
SaveIsDifferentFrom.
bool IsThisFirstTimeUser ()
IsThisFirstTimeUser.
void unHoldPTT ()
unHoldPTT
void holdPTT (int duration)
holdPTT
int CompareSaves (QJsonObject newObject)
CompareSaves Will comparse old and new save and prompt user if a change was detected. Seems a litle bit redundant with SaveIsDifferentFrom(QJsonObject newObject); TODO: is it tho?
void addShowFlag (LIDL::SHOW_SETTINGS addedFlag)
addShowFlag Will add a flag to the list of things to be displayed (stored as flags)
void removeShowFlag (LIDL::SHOW_SETTINGS removedFlag)
removeShowFlag Will remove a flag to the list of things to be displayed (stored as flags)
bool checkShowFlags (LIDL::SHOW_SETTINGS checkedFlag) const
checkShowFlags
LIDL::SHOW_SETTINGS getShowFlags () const
getShowFlags Get the flags
QStringList GetSupportedMimeTypes () const
GetSupportedMimeTypes.
bool GetDragAndDropSeveralWrappers () const
GetDragAndDropSeveralWrappers.
bool getEventProcessing () const
bool isEditing () const
isEditing Is editing basically serves to know whether we should process shortcuts being pressed and play the sound, or not because the user is editing a sound (or in another menu for instance) The boolean will be set in the constructor of the soundwrapper (wrapperproperties) edition window, and unset in the destructor
void setEditing (bool)
setEditing Allows shortcut to be dismissed if they are pressed while a user is editing a wrapper (see isEditing())
Static Public Member Functions
static SettingsController * GetInstance ()
Private Member Functions
SettingsController ()
Private Attributes
QString fileName
bool _isEditing
QString defaultSoundboardFolder
QString defaultSoundsFolder
int recentFileCount
int defaultMainVolume
int defaultVacVolume
std::deque< QFileInfo > recentFiles
Ui::Settings * ui
QMenu * _recentMenu
QJsonObject oldObject
bool fileAlreadyExisted
QTimer _activePttTimer
int _activePttScanCode
int _activePttVitualKey
bool _eventProcessing
LIDL::SHOW_SETTINGS _showFlags
bool dragAndDropSeveralWrappers
Static Private Attributes
static SettingsController * self = nullptr
Constructor & Destructor Documentation
SettingsController()
LIDL::Controller::SettingsController::SettingsController () private
References _activePttTimer, _eventProcessing, _isEditing, _showFlags, defaultMainVolume, defaultSoundboardFolder, defaultSoundsFolder, defaultVacVolume, dragAndDropSeveralWrappers, fileName, LIDL::NO_SETTINGS, recentFileCount, and unHoldPTT().
Referenced by GetInstance().
Member Function Documentation
addFileToRecent
void LIDL::Controller::SettingsController::addFileToRecent (QFileInfo fileInfo) slot
addFileToRecent
Parameters
fileInfo
References recentFiles, and RecentFilesChanged().
Referenced by SoundboardMainUI::SoundboardMainUI().
addShowFlag()
void LIDL::Controller::SettingsController::addShowFlag (LIDL::SHOW_SETTINGS addedFlag)
addShowFlag Will add a flag to the list of things to be displayed (stored as flags)
Parameters
addedFlag
References _showFlags.
Referenced by SoundboardMainUI::Open(), and SoundboardMainUI::setUpMenu().
buttonBrowseLidl
void LIDL::Controller::SettingsController::buttonBrowseLidl () slot
buttonBrowseLidl Slot connected to a file browser button TODO: refactor as a lambda
References ui.
Referenced by ShowSettingsWindow().
buttonBrowseSound
void LIDL::Controller::SettingsController::buttonBrowseSound () slot
buttonBrowseSound Slot connected to a file browser button TODO: refactor as a lambda
References ui.
Referenced by ShowSettingsWindow().
checkShowFlags()
bool LIDL::Controller::SettingsController::checkShowFlags (LIDL::SHOW_SETTINGS checkedFlag) const
checkShowFlags
Parameters
checkedFlag$ Will check if a flag is activated (using &)
Returns
References _showFlags.
Referenced by SoundboardMainUI::refreshView().
CompareSaves()
int LIDL::Controller::SettingsController::CompareSaves (QJsonObject newObject)
CompareSaves Will comparse old and new save and prompt user if a change was detected. Seems a litle bit redundant with SaveIsDifferentFrom(QJsonObject newObject); TODO: is it tho?
Parameters
newObject
Returns
eShrug
References oldObject, and SaveSettings().
GetDefaultMainVolume()
int LIDL::Controller::SettingsController::GetDefaultMainVolume () const
GetDefaultMainVolume.
Returns
The default main volume (either 100 or defined by the opened json)
References defaultMainVolume.
Referenced by SoundboardMainUI::Open().
GetDefaultSoundboardFolder()
QString LIDL::Controller::SettingsController::GetDefaultSoundboardFolder () const
GetDefaultSoundboardFolder.
Returns
The default soundboard folder (either the folder where lidl soundboard is installed, or set by the opened json)
References defaultSoundboardFolder.
GetDefaultSoundFolder()
QString LIDL::Controller::SettingsController::GetDefaultSoundFolder () const
GetDefaultSoundFolder.
Returns
The default soundboard folder (either the folder where lidl soundboard is installed, or set by the opened json)
References defaultSoundsFolder.
GetDefaultVacVolume()
int LIDL::Controller::SettingsController::GetDefaultVacVolume () const
GetDefaultVacVolume.
Returns
The default VAC volume (either 100 or defined by the opened json)
References defaultVacVolume.
Referenced by SoundboardMainUI::Open().
GetDragAndDropSeveralWrappers()
bool LIDL::Controller::SettingsController::GetDragAndDropSeveralWrappers () const
GetDragAndDropSeveralWrappers.
Returns
The behavior of the drag and drop
References dragAndDropSeveralWrappers.
Referenced by SoundboardMainUI::dropEvent().
getEventProcessing()
bool LIDL::Controller::SettingsController::getEventProcessing () const
Returns
bool
References _eventProcessing.
GetInstance()
SettingsController * LIDL::Controller::SettingsController::GetInstance () static
References SettingsController().
Referenced by WrapperProperties::AddSound(), SoundboardMainUI::addSound(), WrapperProperties::AddSoundFromDrop(), WrapperProperties::AddSoundFromUrl(), WrapperProperties::closeEvent(), SoundboardMainUI::closeEvent(), CustomListWidget::dragEnterEvent(), SoundboardMainUI::dragEnterEvent(), SoundboardMainUI::dropEvent(), SoundboardMainUI::GenerateSaveFile(), SoundboardMainUI::Open(), SoundboardMainUI::OpenEXPSounboard(), SoundboardMainUI::OpenSlot(), SoundboardMainUI::PostConstruction(), SoundboardMainUI::refreshView(), SoundboardMainUI::SaveAs(), SoundboardMainUI::SetStatusTextEditText(), SoundboardMainUI::setUpMenu(), SoundboardMainUI::SetUpRecentMenu(), SoundboardMainUI::SoundboardMainUI(), SoundboardMainUI::winHotKeyPressed(), and WrapperProperties::WrapperProperties().
GetLastOpenedSoundboard()
QString LIDL::Controller::SettingsController::GetLastOpenedSoundboard ()
GetLastOpenedSoundboard.
Returns
The most recent opened soundboard, so we can open it automatically for the user
TODO: probably add an option to toggle this off
References recentFiles.
GetRecentFiles()
std::deque< QFileInfo > LIDL::Controller::SettingsController::GetRecentFiles ()
GetRecentFiles.
Returns
A deck of the recently opened files
References recentFiles.
GetRecentFilesCount()
int LIDL::Controller::SettingsController::GetRecentFilesCount () const
GetRecentFilesCount.
Returns
The count of recent files stored inside lidlsettings
References recentFileCount.
Referenced by SoundboardMainUI::SetUpRecentMenu().
getShowFlags()
LIDL::SHOW_SETTINGS LIDL::Controller::SettingsController::getShowFlags () const
getShowFlags Get the flags
Returns
the flags :)
References _showFlags.
GetSupportedMimeTypes()
QStringList LIDL::Controller::SettingsController::GetSupportedMimeTypes () const
GetSupportedMimeTypes.
Returns
The list of supported MIME types for the player as a QStringList (QList<QString>)
Referenced by WrapperProperties::AddSoundFromUrl(), and SoundboardMainUI::dropEvent().
holdPTT()
void LIDL::Controller::SettingsController::holdPTT (int duration)
holdPTT
Will hold push to talk key for given duration. If several sounds are played, it will hold it for the longest duration. Interally this uses a timer that will be reset if (new duration > old duration)
Parameters
duration The duration to hold the PTT for
References _activePttScanCode, _activePttTimer, _activePttVitualKey, _eventProcessing, and LIDL::Controller::ProfileController::GetInstance().
Referenced by SoundboardMainUI::addSound().
isEditing()
bool LIDL::Controller::SettingsController::isEditing () const
isEditing Is editing basically serves to know whether we should process shortcuts being pressed and play the sound, or not because the user is editing a sound (or in another menu for instance) The boolean will be set in the constructor of the soundwrapper (wrapperproperties) edition window, and unset in the destructor
Returns
boolean
References _isEditing.
Referenced by SoundboardMainUI::winHotKeyPressed().
IsThisFirstTimeUser()
bool LIDL::Controller::SettingsController::IsThisFirstTimeUser ()
IsThisFirstTimeUser.
Returns
true if first time user, so we show the welcome message
References fileAlreadyExisted.
OpenSettings()
bool LIDL::Controller::SettingsController::OpenSettings ()
OpenSettings.
Used to open the lidlsettings.json file, that contain several stuff such as default locations, default volumes, and recent files. Will probably contain profiles later on :)
Returns
true if it was opened, false otherwise
References defaultMainVolume, defaultSoundboardFolder, defaultSoundsFolder, defaultVacVolume, dragAndDropSeveralWrappers, fileAlreadyExisted, fileName, recentFileCount, recentFiles, RecentFilesChanged(), and SaveSettings().
ProfileConfigurationChanged
void LIDL::Controller::SettingsController::ProfileConfigurationChanged () signal
RecentFilesChanged
void LIDL::Controller::SettingsController::RecentFilesChanged () signal
RecentFilesChanged Signal is caught by the main UI to changes the Open Recent Menu.
Referenced by addFileToRecent(), OpenSettings(), and SoundboardMainUI::SoundboardMainUI().
removeShowFlag()
void LIDL::Controller::SettingsController::removeShowFlag (LIDL::SHOW_SETTINGS removedFlag)
removeShowFlag Will remove a flag to the list of things to be displayed (stored as flags)
Parameters
removedFlag
References _showFlags.
Referenced by SoundboardMainUI::setUpMenu().
SaveIsDifferentFrom()
bool LIDL::Controller::SettingsController::SaveIsDifferentFrom (QJsonObject newObject)
SaveIsDifferentFrom.
Parameters
newObject A json "snapshot" from the soundboard
Returns
Result of comparison between "old" snapshot and this one TODO: account for profiles
References oldObject.
SaveSettings()
void LIDL::Controller::SettingsController::SaveSettings ()
SaveSettings.
Will save settings to lidlsettings.json
References defaultMainVolume, defaultSoundboardFolder, defaultSoundsFolder, defaultVacVolume, dragAndDropSeveralWrappers, fileName, recentFileCount, and recentFiles.
Referenced by SoundboardMainUI::closeEvent(), CompareSaves(), and OpenSettings().
SaveState()
void LIDL::Controller::SettingsController::SaveState (QJsonObject object)
SaveState.
Parameters
object A json "snapshot" from the soundboard TODO: account for profiles
References oldObject.
Referenced by SoundboardMainUI::PostConstruction(), and SoundboardMainUI::SoundboardMainUI().
SetDefaultMainVolume
void LIDL::Controller::SettingsController::SetDefaultMainVolume (int newVolume) slot
SetDefaultMainVolume Sets the default main volume inside the controller, to be used when creating wrappers, and saved in the lidlsettings.
References defaultMainVolume.
Referenced by ShowSettingsWindow().
SetDefaultVacVolume
void LIDL::Controller::SettingsController::SetDefaultVacVolume (int newVolume) slot
SetDefaultVacVolume Sets the default VAC volume inside the controller, to be used when creating wrappers, and saved in the lidlsettings.
References defaultVacVolume.
Referenced by ShowSettingsWindow().
setEditing()
void LIDL::Controller::SettingsController::setEditing (bool newState)
setEditing Allows shortcut to be dismissed if they are pressed while a user is editing a wrapper (see isEditing())
References _isEditing.
Referenced by WrapperProperties::closeEvent(), and WrapperProperties::WrapperProperties().
SetPTTScanCode
void LIDL::Controller::SettingsController::SetPTTScanCode (int sc) slot
SetPTTScanCode Register the key to be auto-held while playing a sound.
Parameters
sc The key scan code
References _activePttScanCode.
SetPTTVirtualKey
void LIDL::Controller::SettingsController::SetPTTVirtualKey (int vk) slot
SetPTTVirtualKey Register the key to be auto-held while playing a sound.
Parameters
vk The key virtual key
References _activePttVitualKey.
SetRecentFileCount
void LIDL::Controller::SettingsController::SetRecentFileCount (int count) slot
References recentFileCount.
Referenced by ShowSettingsWindow().
SettingsChanged
void LIDL::Controller::SettingsController::SettingsChanged () signal
Referenced by SoundboardMainUI::SoundboardMainUI().
ShowSettingsWindow
void LIDL::Controller::SettingsController::ShowSettingsWindow () slot
References buttonBrowseLidl(), buttonBrowseSound(), defaultMainVolume, defaultSoundboardFolder, defaultSoundsFolder, defaultVacVolume, dragAndDropSeveralWrappers, recentFileCount, SetDefaultMainVolume(), SetDefaultVacVolume(), SetRecentFileCount(), ui, and void().
unHoldPTT()
void LIDL::Controller::SettingsController::unHoldPTT ()
unHoldPTT
Will unhold the push to talk (when using auto hold ptt)
References _activePttTimer, and LIDL::Controller::ProfileController::GetInstance().
Referenced by SettingsController(), SoundboardMainUI::SoundboardMainUI(), and SoundboardMainUI::winHotKeyPressed().
Member Data Documentation
_activePttScanCode
int LIDL::Controller::SettingsController::_activePttScanCode private
Referenced by holdPTT(), and SetPTTScanCode().
_activePttTimer
QTimer LIDL::Controller::SettingsController::_activePttTimer private
Referenced by holdPTT(), SettingsController(), and unHoldPTT().
_activePttVitualKey
int LIDL::Controller::SettingsController::_activePttVitualKey private
Referenced by holdPTT(), and SetPTTVirtualKey().
_eventProcessing
bool LIDL::Controller::SettingsController::_eventProcessing private
boolean to be tested in MainUI to know if events (key sequences) should be processed
Referenced by getEventProcessing(), holdPTT(), and SettingsController().
_isEditing
bool LIDL::Controller::SettingsController::_isEditing private
Referenced by isEditing(), setEditing(), and SettingsController().
_recentMenu
QMenu* LIDL::Controller::SettingsController::_recentMenu private
_showFlags
LIDL::SHOW_SETTINGS LIDL::Controller::SettingsController::_showFlags private
Referenced by addShowFlag(), checkShowFlags(), getShowFlags(), removeShowFlag(), and SettingsController().
defaultMainVolume
int LIDL::Controller::SettingsController::defaultMainVolume private
Referenced by GetDefaultMainVolume(), OpenSettings(), SaveSettings(), SetDefaultMainVolume(), SettingsController(), and ShowSettingsWindow().
defaultSoundboardFolder
QString LIDL::Controller::SettingsController::defaultSoundboardFolder private
Referenced by GetDefaultSoundboardFolder(), OpenSettings(), SaveSettings(), SettingsController(), and ShowSettingsWindow().
defaultSoundsFolder
QString LIDL::Controller::SettingsController::defaultSoundsFolder private
Referenced by GetDefaultSoundFolder(), OpenSettings(), SaveSettings(), SettingsController(), and ShowSettingsWindow().
defaultVacVolume
int LIDL::Controller::SettingsController::defaultVacVolume private
Referenced by GetDefaultVacVolume(), OpenSettings(), SaveSettings(), SetDefaultVacVolume(), SettingsController(), and ShowSettingsWindow().
dragAndDropSeveralWrappers
bool LIDL::Controller::SettingsController::dragAndDropSeveralWrappers private
Boolean holding how drag and drop several files will be handled (several wrapper or one)
Referenced by GetDragAndDropSeveralWrappers(), OpenSettings(), SaveSettings(), SettingsController(), and ShowSettingsWindow().
fileAlreadyExisted
bool LIDL::Controller::SettingsController::fileAlreadyExisted private
Referenced by IsThisFirstTimeUser(), and OpenSettings().
fileName
QString LIDL::Controller::SettingsController::fileName private
Referenced by OpenSettings(), SaveSettings(), and SettingsController().
oldObject
QJsonObject LIDL::Controller::SettingsController::oldObject private
Referenced by CompareSaves(), SaveIsDifferentFrom(), and SaveState().
recentFileCount
int LIDL::Controller::SettingsController::recentFileCount private
Referenced by GetRecentFilesCount(), OpenSettings(), SaveSettings(), SetRecentFileCount(), SettingsController(), and ShowSettingsWindow().
recentFiles
std::deque<QFileInfo> LIDL::Controller::SettingsController::recentFiles private
Referenced by addFileToRecent(), GetLastOpenedSoundboard(), GetRecentFiles(), OpenSettings(), and SaveSettings().
self
SettingsController * LIDL::Controller::SettingsController::self = nullptr static private
ui
Ui::Settings* LIDL::Controller::SettingsController::ui private
Referenced by buttonBrowseLidl(), buttonBrowseSound(), and ShowSettingsWindow().
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/SettingsController.h
D:/Qt/Projects/Lidl_Soundboard/SettingsController.cpp