LIDL Soundboard: GameSelector Class Reference
GameSelector Class Reference
#include <GameSelector.h>
Public Slots
void RefreshProfiles ()
RefreshProfiles.
Signals
void RefreshWrappers (QVector< std::shared_ptr< SoundWrapper >>)
Public Member Functions
GameSelector (QWidget *parent=nullptr)
Public Attributes
Ui::GameSelector * _gameSelectorUi
ProfileEdit * _profileEdit
Constructor & Destructor Documentation
GameSelector()
GameSelector::GameSelector (QWidget * parent = nullptr)
References _gameSelectorUi, LIDL::Controller::ProfileController::GetInstance(), LIDL::Controller::ProfileController::ManualGameConfigurationChanged(), LIDL::Controller::ProfileController::ProfileConfigurationChanged(), RefreshProfiles(), and void().
Member Function Documentation
RefreshProfiles
void GameSelector::RefreshProfiles () slot
RefreshProfiles.
Will refresh the combo box and fill it with the available profiles. Will also re-load the active profile. However it will prevent the combobox from emitting event to avoid infinite recursion. It will MANUALLY call the function to AddSounds in the UI. See ProfileController.h for more details
References _gameSelectorUi, LIDL::Controller::ProfileController::GetActiveProfile(), LIDL::Controller::ProfileController::GetInstance(), Profile::GetName(), LIDL::Controller::ProfileController::GetProfiles(), and RefreshWrappers().
Referenced by GameSelector().
RefreshWrappers
void GameSelector::RefreshWrappers () signal
Referenced by RefreshProfiles(), and SoundboardMainUI::SoundboardMainUI().
Member Data Documentation
_gameSelectorUi
Ui::GameSelector* GameSelector::_gameSelectorUi
Referenced by GameSelector(), and RefreshProfiles().
_profileEdit
ProfileEdit* GameSelector::_profileEdit
The documentation for this class was generated from the following files:
D:/Qt/Projects/Lidl_Soundboard/include/GameSelector.h
D:/Qt/Projects/Lidl_Soundboard/GameSelector.cpp