LIDL Soundboard: LIDL::Callback Namespace Reference
LIDL::Callback Namespace Reference
Functions
void CALLBACK ResizeToWindow (HWINEVENTHOOK hook, DWORD event, HWND hwnd, LONG idObject, LONG idChild, DWORD dwEventThread, DWORD dwmsEventTime)
ResizeToWindow.
void CALLBACK ShowOverlay (HWINEVENTHOOK hook, DWORD event, HWND hwnd, LONG idObject, LONG idChild, DWORD dwEventThread, DWORD dwmsEventTime)
ShowOverlay.
Function Documentation
ResizeToWindow()
void CALLBACK LIDL::Callback::ResizeToWindow (HWINEVENTHOOK hook, DWORD event, HWND hwnd, LONG idObject, LONG idChild, DWORD dwEventThread, DWORD dwmsEventTime)
ResizeToWindow.
Parameters
hook
event
hwnd
idObject
idChild
dwEventThread
dwmsEventTime Used to call LIDL::OverlayController::GetInstance()->ResizeToWindow(GetForegroundWindow()); On: EVENT_SYSTEM_MOVESIZEEND (GetForegroundWindow() is defined in winuser.h)
References LIDL::OverlayController::GetInstance(), and LIDL::OverlayController::ResizeToWindow().
Referenced by LIDL::Controller::HookController::SetHooks().
ShowOverlay()
void CALLBACK LIDL::Callback::ShowOverlay (HWINEVENTHOOK hook, DWORD event, HWND hwnd, LONG idObject, LONG idChild, DWORD dwEventThread, DWORD dwmsEventTime)
ShowOverlay.
Parameters
hook
event
hwnd
idObject
idChild
dwEventThread
dwmsEventTime Used to call LIDL::OverlayController::GetInstance()->ResizeToWindow(GetForegroundWindow()); LIDL::OverlayController::GetInstance()->ShowGameOverlay(GetForegroundWindow()); On: EVENT_SYSTEM_MOVESIZEEND, EVENT_SYSTEM_MINIMIZEEND, EVENT_SYSTEM_MINIMIZESTART (GetForegroundWindow() is defined in winuser.h)
References LIDL::OverlayController::GetInstance(), LIDL::Controller::HookController::GetProfileForExe(), LIDL::OverlayController::ResizeToWindow(), and LIDL::OverlayController::ShowGameOverlay().
Referenced by LIDL::Controller::HookController::SetHooks().